-- ============================================================================
-- Migration: 20261007000003_seed_compendium.sql
-- Description: Seed master compendium data from DD_DATA
-- ============================================================================

-- 1. Abilities & Skills
INSERT INTO public.abilities (id, name, short_code, dnd_equiv, description) VALUES ('physique', 'Physique', 'PHY', 'STR / DEX / CON', 'Kekuatan otot, kelenturan tubuh, refleks motorik, dan daya tahan fisik.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, short_code = EXCLUDED.short_code, dnd_equiv = EXCLUDED.dnd_equiv, description = EXCLUDED.description;
INSERT INTO public.skills (id, ability_id, name, description) VALUES ('power', 'physique', 'Power', 'Angkat beban, mendobrak pintu, memukul, mendorong, dan adu tenaga fisik.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description;
INSERT INTO public.skills (id, ability_id, name, description) VALUES ('agility', 'physique', 'Agility', 'Kelincahan, kecepatan refleks, kejar kereta, panjat pagar sekolah, dan kelenturan.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description;
INSERT INTO public.skills (id, ability_id, name, description) VALUES ('stamina', 'physique', 'Stamina', 'Daya tahan lari maraton, begadang belajar, tahan benturan, dan tidak mudah masuk angin.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description;
INSERT INTO public.abilities (id, name, short_code, dnd_equiv, description) VALUES ('intelligent', 'Intelligent', 'INT', 'INT / Logic', 'Kecerdasan akademis, nalar logika, pemecahan masalah, dan pengetahuan jalanan.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, short_code = EXCLUDED.short_code, dnd_equiv = EXCLUDED.dnd_equiv, description = EXCLUDED.description;
INSERT INTO public.skills (id, ability_id, name, description) VALUES ('academic', 'intelligent', 'Academic', 'Materi ujian sekolah, rumus matematika/sains, sejarah, dan hafalan teori pelajaran.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description;
INSERT INTO public.skills (id, ability_id, name, description) VALUES ('people', 'intelligent', 'People', 'Membaca psikologi lawan, menganalisis bahasa tubuh, mendeteksi motif bohong/salting.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description;
INSERT INTO public.skills (id, ability_id, name, description) VALUES ('street', 'intelligent', 'Street', 'Akal-akalan pergaulan, tahu jalan pintas rahasia kota, gosip geng, dan trik bertahan di jalanan.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description;
INSERT INTO public.abilities (id, name, short_code, dnd_equiv, description) VALUES ('looks', 'Looks', 'LOK', 'CHA / Attractiveness', 'Daya tarik visual, pesona karismatik, gaya berpakaian, dan aura kehadiran.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, short_code = EXCLUDED.short_code, dnd_equiv = EXCLUDED.dnd_equiv, description = EXCLUDED.description;
INSERT INTO public.skills (id, ability_id, name, description) VALUES ('charm', 'looks', 'Charm', 'Pesona personal, senyuman menawan, rayuan asmara, kedipan mata, dan daya pikat alami.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description;
INSERT INTO public.skills (id, ability_id, name, description) VALUES ('influence', 'looks', 'Influence', 'Pengaruh reputasi di kalangan murid, disegani kawan dan lawan, serta wibawa status.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description;
INSERT INTO public.skills (id, ability_id, name, description) VALUES ('aura', 'looks', 'Aura', 'Kehadiran yang mencolok, tatapan tajam berkarisma, atau vibes misterius yang membius.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description;
INSERT INTO public.abilities (id, name, short_code, dnd_equiv, description) VALUES ('mind', 'Mind', 'MND', 'WIS / Mental Fortitude', 'Kekuatan mental, ketenangan batin, empati, dan kepekaan membaca atmosfer sekitar.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, short_code = EXCLUDED.short_code, dnd_equiv = EXCLUDED.dnd_equiv, description = EXCLUDED.description;
INSERT INTO public.skills (id, ability_id, name, description) VALUES ('emotional', 'mind', 'Emotional', 'Kontrol emosi pribadi, jaga imej (jaim), menahan rasa malu, dan mengelola kegelisahan hati.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description;
INSERT INTO public.skills (id, ability_id, name, description) VALUES ('interpersonal', 'mind', 'Interpersonal', 'Peka terhadap perasaan orang lain, mendengarkan curhat, merajut ikatan hati mendalam.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description;
INSERT INTO public.skills (id, ability_id, name, description) VALUES ('awareness', 'mind', 'Awareness', 'Membaca atmosfer sosial (Kuuki Yomenai / Kuuki Yomeru), menyadari tatapan rahasia orang lain.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description;
INSERT INTO public.abilities (id, name, short_code, dnd_equiv, description) VALUES ('talent', 'Talent', 'TLN', 'Performance / Creativity', 'Bakat alami, ekspresi kesenian, keahlian panggung, dan keluwesan berimprovisasi.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, short_code = EXCLUDED.short_code, dnd_equiv = EXCLUDED.dnd_equiv, description = EXCLUDED.description;
INSERT INTO public.skills (id, ability_id, name, description) VALUES ('creative', 'talent', 'Creative', 'Merancang ide festival sekolah, menulis surat cinta puitis, ilustrasi, dan desain kreatif.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description;
INSERT INTO public.skills (id, ability_id, name, description) VALUES ('performance', 'talent', 'Performance', 'Akting panggung drama, bernyanyi, memainkan instrumen musik, dan pidato membakar semangat.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description;
INSERT INTO public.skills (id, ability_id, name, description) VALUES ('adaptability', 'talent', 'Adaptability', 'Improvisasi kilat saat rencana berantakan, mengubah suasana kaku, dan fleksibel menghadapi situasi.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description;
INSERT INTO public.abilities (id, name, short_code, dnd_equiv, description) VALUES ('luck', 'Luck', 'LCK', 'Fate / Fortune', 'Faktor keberuntungan murni, takdir kasmaran, dan kebetulan-kebetulan dramatis anime.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, short_code = EXCLUDED.short_code, dnd_equiv = EXCLUDED.dnd_equiv, description = EXCLUDED.description;
INSERT INTO public.skills (id, ability_id, name, description) VALUES ('relationship_luck', 'luck', 'Relationship Luck', 'Papasan romantis tidak sengaja, tabrakan bawa roti di tikungan, terlindung payung bareng saat hujan.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description;
INSERT INTO public.skills (id, ability_id, name, description) VALUES ('situation_luck', 'luck', 'Situation Luck', 'Lolos razia sidak guru BP, nemu uang di jalan, guru killer izin tidak masuk kelas.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description;
INSERT INTO public.skills (id, ability_id, name, description) VALUES ('academic_luck', 'luck', 'Academic Luck', 'Hoki tebak kancing saat ujian, materi yang dipelajari semalam pas keluar di lembar soal.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description;

-- 2. Ekskul (Classes), Subclasses, and Club Moves
INSERT INTO public.ekskul (id, name, tagline, hit_die, primary_stat, saving_throws, perk_description) VALUES ('student_council', 'Student Council (OSIS)', 'Elit Organisasi & Penegak Ketertiban Sekolah', 'd8', 'Looks / Intelligent', ARRAY['intelligent', 'looks']::TEXT[], 'Hak akses ruang OSIS ber-AC, wewenang menegur murid lain, anggaran proposal kegiatan sekolah, dan disegani dewan guru.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, tagline = EXCLUDED.tagline, hit_die = EXCLUDED.hit_die, primary_stat = EXCLUDED.primary_stat, saving_throws = EXCLUDED.saving_throws, perk_description = EXCLUDED.perk_description;
INSERT INTO public.ekskul_subclasses (id, ekskul_id, name, description) VALUES ('presidium', 'student_council', 'Ketua / Presidium', 'Pemimpin mutlak OSIS. Bonus +2 pada semua Looks checks saat berhadapan dengan guru atau undangan eksternal.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description;
INSERT INTO public.ekskul_subclasses (id, ekskul_id, name, description) VALUES ('discipline', 'student_council', 'Divisi Kedisiplinan', 'Penegak aturan sekolah. Advantage pada Intimidasi dan Check untuk mendeteksi pelanggaran murid lain.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description;
INSERT INTO public.ekskul (id, name, tagline, hit_die, primary_stat, saving_throws, perk_description) VALUES ('kendo', 'Kendo (Pedang Bambu)', 'Disiplin Pedang Samurai & Konsentrasi Batin', 'd10', 'Physique / Mind', ARRAY['physique', 'mind']::TEXT[], 'Penguasaan teknik Shinai dan Bokken, ruang latihan Dojo tradisional, kuda-kuda kokoh, dan fokus mata yang tak goyah.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, tagline = EXCLUDED.tagline, hit_die = EXCLUDED.hit_die, primary_stat = EXCLUDED.primary_stat, saving_throws = EXCLUDED.saving_throws, perk_description = EXCLUDED.perk_description;
INSERT INTO public.ekskul_subclasses (id, ekskul_id, name, description) VALUES ('men_striker', 'kendo', 'Gaya Serangan Kilat (Men-Striker)', 'Spesialisasi serangan cepat. Bonus aksi ekstra setelah serangan sukses pertama dalam ronde.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description;
INSERT INTO public.ekskul_subclasses (id, ekskul_id, name, description) VALUES ('iron_guard', 'kendo', 'Gaya Pertahanan Keras (Iron Wall)', 'Spesialisasi pertahanan. +1 Physical AC permanen dan Advantage pada Physique Saving Throw.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description;
INSERT INTO public.ekskul (id, name, tagline, hit_die, primary_stat, saving_throws, perk_description) VALUES ('martial_arts', 'Martial Arts (Beladiri / Karate / Judo)', 'Pertarungan Jarak Dekat & Refleks Bantingan', 'd10', 'Physique', ARRAY['physique', 'talent']::TEXT[], 'Tubuh liat tahan banting, pukulan dan tendangan tanpa senjata berdaya hancur tinggi, serta kemampuan melumpuhkan lawan tanpa senjata tajam.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, tagline = EXCLUDED.tagline, hit_die = EXCLUDED.hit_die, primary_stat = EXCLUDED.primary_stat, saving_throws = EXCLUDED.saving_throws, perk_description = EXCLUDED.perk_description;
INSERT INTO public.ekskul_subclasses (id, ekskul_id, name, description) VALUES ('grappler', 'martial_arts', 'Spesialis Bantingan (Judo / Grappler)', 'Ahli merebut dan membanting lawan ke tanah. Serangan Bantingan memberikan +2d4 damage tambahan.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description;
INSERT INTO public.ekskul_subclasses (id, ekskul_id, name, description) VALUES ('striker', 'martial_arts', 'Spesialis Serangan Beruntun (Striker)', 'Ahli combo pukulan cepat. Bisa menyerang 2 kali dengan 1 aksi (setelah level 3+).') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description;
INSERT INTO public.ekskul (id, name, tagline, hit_die, primary_stat, saving_throws, perk_description) VALUES ('sports', 'Sports (Sepak Bola / Basket / Atletik)', 'Stamina Baja & Kecepatan Lapangan Terbuka', 'd10', 'Physique / Looks', ARRAY['physique', 'physique']::TEXT[], 'Kecepatan lari di atas rata-rata (+10 ft speed), keringat karismatik yang digemari murid lain, dan stamina tahan maraton.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, tagline = EXCLUDED.tagline, hit_die = EXCLUDED.hit_die, primary_stat = EXCLUDED.primary_stat, saving_throws = EXCLUDED.saving_throws, perk_description = EXCLUDED.perk_description;
INSERT INTO public.ekskul_subclasses (id, ekskul_id, name, description) VALUES ('ace_striker', 'sports', 'Striker / Ace Lapangan', 'Serangan fisik berbasis kecepatan. Bonus +1d4 damage saat menyerang setelah berlari setidaknya 15 ft.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description;
INSERT INTO public.ekskul_subclasses (id, ekskul_id, name, description) VALUES ('team_captain', 'sports', 'Kapten Regu', 'Pemimpin tim. Sekali per istirahat, berikan 1d6 Inspiration Die ke seluruh anggota tim.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description;
INSERT INTO public.ekskul (id, name, tagline, hit_die, primary_stat, saving_throws, perk_description) VALUES ('drama', 'Drama Club (Teater & Seni Peran)', 'Manipulasi Emosi, Akting Panggung & Dusta Sempurna', 'd8', 'Looks / Talent', ARRAY['looks', 'talent']::TEXT[], 'Kostum panggung beragam, kemampuan meneteskan air mata buatan seketika, menirukan intonasi orang lain, dan menyamar.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, tagline = EXCLUDED.tagline, hit_die = EXCLUDED.hit_die, primary_stat = EXCLUDED.primary_stat, saving_throws = EXCLUDED.saving_throws, perk_description = EXCLUDED.perk_description;
INSERT INTO public.ekskul_subclasses (id, ekskul_id, name, description) VALUES ('lead_actor', 'drama', 'Aktor Protagonis / Bintang Panggung', 'Ahli menarik simpati massa. Serangan sosial berbasis Looks memberikan 1d4 bonus damage Composure.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description;
INSERT INTO public.ekskul_subclasses (id, ekskul_id, name, description) VALUES ('antagonist', 'drama', 'Master Tipu Daya (Antagonist)', 'Ahli manipulasi. Advantage pada semua check untuk menipu, berpura-pura, atau menyamar.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description;
INSERT INTO public.ekskul (id, name, tagline, hit_die, primary_stat, saving_throws, perk_description) VALUES ('kir_osn', 'KIR / OSN (Sains & Karya Ilmiah Remaja)', 'Analisis Tajam, Riset Ilmiah & Reaksi Kimia', 'd6', 'Intelligent', ARRAY['intelligent', 'mind']::TEXT[], 'Kunci akses laboratorium sains & bahan kimia, bank soal olimpiade, mikroskop, dan laptop penuh data analisis.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, tagline = EXCLUDED.tagline, hit_die = EXCLUDED.hit_die, primary_stat = EXCLUDED.primary_stat, saving_throws = EXCLUDED.saving_throws, perk_description = EXCLUDED.perk_description;
INSERT INTO public.ekskul_subclasses (id, ekskul_id, name, description) VALUES ('chemist', 'kir_osn', 'Peneliti Kimia & Biologi', 'Ahli senyawa kimia. Bisa menciptakan efek racun, asap, atau pelemas otot dari bahan lab sekali per sesi.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description;
INSERT INTO public.ekskul_subclasses (id, ekskul_id, name, description) VALUES ('hacker', 'kir_osn', 'Hacker Komputer & Robotika', 'Ahli perangkat digital. Advantage pada check Intelligent untuk membobol sistem, CCTV, atau kunci digital.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description;
INSERT INTO public.ekskul (id, name, tagline, hit_die, primary_stat, saving_throws, perk_description) VALUES ('pramuka_paskin', 'Pramuka / Paskin (Paskibra & Kedisiplinan Baris)', 'Tali Temali, Disiplin Militer & Postur Tegak', 'd10', 'Physique / Mind', ARRAY['physique', 'mind']::TEXT[], 'Keahlian tali temali mengikat barang/lawan, tiang bendera serbaguna, peluit komando, dan daya tahan berjemur di lapangan.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, tagline = EXCLUDED.tagline, hit_die = EXCLUDED.hit_die, primary_stat = EXCLUDED.primary_stat, saving_throws = EXCLUDED.saving_throws, perk_description = EXCLUDED.perk_description;
INSERT INTO public.ekskul_subclasses (id, ekskul_id, name, description) VALUES ('danton', 'pramuka_paskin', 'Komandan Peleton (Danton)', 'Pemimpin barisan. Advantage saat memimpin aksi kelompok, bonus +2 pada semua Social Saves tim.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description;
INSERT INTO public.ekskul_subclasses (id, ekskul_id, name, description) VALUES ('pioneer', 'pramuka_paskin', 'Pionir Tali Temali & Tenda', 'Ahli bertahan hidup. Tidak pernah kehilangan arah di luar ruangan. +2 Physique Save terhadap bahaya alam.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description;
INSERT INTO public.ekskul (id, name, tagline, hit_die, primary_stat, saving_throws, perk_description) VALUES ('pecinta_alam', 'Pecinta Alam (Mapala / Sispala)', 'Insting Bertahan Hidup, Peta Liar & Fisik Tangguh', 'd10', 'Physique / Mind', ARRAY['physique', 'mind']::TEXT[], 'Tenda dome portabel, kompor gas mini, ransel gunung besar (kapasitas tas ekstra), dan indra penciuman cuaca tajam.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, tagline = EXCLUDED.tagline, hit_die = EXCLUDED.hit_die, primary_stat = EXCLUDED.primary_stat, saving_throws = EXCLUDED.saving_throws, perk_description = EXCLUDED.perk_description;
INSERT INTO public.ekskul_subclasses (id, ekskul_id, name, description) VALUES ('explorer', 'pecinta_alam', 'Penjelajah Rimba & Pendaki', 'Spesialis navigasi dan terrain. Advantage pada Physique checks untuk memanjat, berenang, atau melintasi rintangan alam.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description;
INSERT INTO public.ekskul_subclasses (id, ekskul_id, name, description) VALUES ('medic', 'pecinta_alam', 'Ahli Pertolongan Pertama (Medic)', 'Spesialis penyembuhan lapangan. Heal dice meningkat jadi 1d10 dan bisa menyembuhkan 1 teman per Short Rest.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description;
INSERT INTO public.ekskul (id, name, tagline, hit_die, primary_stat, saving_throws, perk_description) VALUES ('penyiaran', 'Penyiaran (Broadcasting / Radio Sekolah)', 'Suara Emas Penguasa Speaker Sekolah & Intel Gosip', 'd6', 'Looks / Intelligent', ARRAY['intelligent', 'looks']::TEXT[], 'Hak akses ruang siaran audio sekolah, mikrofon, pemutar lagu, dan jaringan informan gosip paling mutakhir di sekolah.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, tagline = EXCLUDED.tagline, hit_die = EXCLUDED.hit_die, primary_stat = EXCLUDED.primary_stat, saving_throws = EXCLUDED.saving_throws, perk_description = EXCLUDED.perk_description;
INSERT INTO public.ekskul_subclasses (id, ekskul_id, name, description) VALUES ('radio_host', 'penyiaran', 'Penyiar Radio Sekolah', 'Suara emas sekolah. Semua Social Moves berbasis suara mendapat +1 ke DC check dan 1d4 bonus damage.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description;
INSERT INTO public.ekskul_subclasses (id, ekskul_id, name, description) VALUES ('investigator', 'penyiaran', 'Reporter Investigasi', 'Ahli menggali informasi. Advantage pada semua check Intelligent (Street) dan Mind (Interpersonal) untuk mencari gosip.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description;
INSERT INTO public.ekskul (id, name, tagline, hit_die, primary_stat, saving_throws, perk_description) VALUES ('literatur', 'Literatur (Klub Sastra & Membaca)', 'Kekuatan Kata Romantis, Sajak & Misteri Buku Lama', 'd6', 'Intelligent / Mind', ARRAY['intelligent', 'mind']::TEXT[], 'Tempat persembunyian tenang di sudut perpustakaan, koleksi novel romansa klasik, kemampuan merangkai surat cinta mematikan.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, tagline = EXCLUDED.tagline, hit_die = EXCLUDED.hit_die, primary_stat = EXCLUDED.primary_stat, saving_throws = EXCLUDED.saving_throws, perk_description = EXCLUDED.perk_description;
INSERT INTO public.ekskul_subclasses (id, ekskul_id, name, description) VALUES ('novelist', 'literatur', 'Penulis Puisi & Novel Romansa', 'Surat cinta dan aksi romansa berbasis Talent/Creative mendapat 1d4 bonus damage Composure.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description;
INSERT INTO public.ekskul_subclasses (id, ekskul_id, name, description) VALUES ('archivist', 'literatur', 'Penjaga Arsip Sejarah Sekolah', 'Ahli sejarah dan dokumen. Advantage pada semua check Intelligent terkait sejarah, peraturan, atau informasi tertulis.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description;
INSERT INTO public.ekskul (id, name, tagline, hit_die, primary_stat, saving_throws, perk_description) VALUES ('band', 'Band Musik (Gitar / Drum / Vokal / Keyboard)', 'Dentuman Distorsi, Semangat Jiwa Muda & Fans Fanatik', 'd8', 'Looks / Talent', ARRAY['looks', 'talent']::TEXT[], 'Studio musik kedap suara, instrumen musik andalan, ampli portabel, pick gitar jimat keberuntungan, dan basis penggemar.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, tagline = EXCLUDED.tagline, hit_die = EXCLUDED.hit_die, primary_stat = EXCLUDED.primary_stat, saving_throws = EXCLUDED.saving_throws, perk_description = EXCLUDED.perk_description;
INSERT INTO public.ekskul_subclasses (id, ekskul_id, name, description) VALUES ('lead_guitar', 'band', 'Lead Guitarist / Soloist', 'Ahli solo gitar. Serangan Sonic berbasis Talent mendapat +1d6 damage dan bisa mempengaruhi area lebih luas.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description;
INSERT INTO public.ekskul_subclasses (id, ekskul_id, name, description) VALUES ('vocalist', 'band', 'Vokalis Utama Karismatik', 'Ahli memikat hati penonton. Semua Social Moves dari vokalis memberikan Disadvantage pada Mental Saves target.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description;
INSERT INTO public.ekskul (id, name, tagline, hit_die, primary_stat, saving_throws, perk_description) VALUES ('painting', 'Painting (Klub Seni Rupa & Desain)', 'Goresan Kuas, Memori Visual Tajam & Estetika Warna', 'd6', 'Talent / Intelligent', ARRAY['intelligent', 'talent']::TEXT[], 'Ruang seni penuh aroma cat minyak, kuas dan kanvas, celemek berlumur cat artistik, dan mata yang peka warna emosi.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, tagline = EXCLUDED.tagline, hit_die = EXCLUDED.hit_die, primary_stat = EXCLUDED.primary_stat, saving_throws = EXCLUDED.saving_throws, perk_description = EXCLUDED.perk_description;
INSERT INTO public.ekskul_subclasses (id, ekskul_id, name, description) VALUES ('portrait', 'painting', 'Pelukis Potret Realis', 'Ahli memvisualisasikan seseorang dari ingatan. Advantage pada check yang membutuhkan deskripsi rupa atau pengenalan wajah.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description;
INSERT INTO public.ekskul_subclasses (id, ekskul_id, name, description) VALUES ('designer', 'painting', 'Ilustrator Manga & Desain', 'Ahli visual komunikasi. Bisa menciptakan publikasi, flyer, atau karikatur yang memberikan 1d6 bonus Influence di lingkungan sekolah.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description;

-- 3. Archetypes (Species / Tropes) & Archetype Moves
INSERT INTO public.archetypes (id, name, tagline, stat_bonus, perk_description) VALUES ('delinquent', 'Delinquent (Berandalan / Yanki)', 'Seragam Dasi Longgar, Tatapan Tajam & Hati Emas Tersembunyi', '{"physique":2,"looks":1}'::jsonb, NULL) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, tagline = EXCLUDED.tagline, stat_bonus = EXCLUDED.stat_bonus, perk_description = EXCLUDED.perk_description;
INSERT INTO public.archetypes (id, name, tagline, stat_bonus, perk_description) VALUES ('jock', 'Jock / Sporty', 'Bugar, Berenergi Tinggi, Semangat Pantang Menyerah', '{"physique":2,"talent":1}'::jsonb, NULL) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, tagline = EXCLUDED.tagline, stat_bonus = EXCLUDED.stat_bonus, perk_description = EXCLUDED.perk_description;
INSERT INTO public.archetypes (id, name, tagline, stat_bonus, perk_description) VALUES ('nerd', 'Nerd (Murid Ambis / Kutu Buku)', 'Kacamata Frame Tebal, Catatan Lengkap & Tahu Segalanya', '{"intelligent":2,"mind":1}'::jsonb, NULL) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, tagline = EXCLUDED.tagline, stat_bonus = EXCLUDED.stat_bonus, perk_description = EXCLUDED.perk_description;
INSERT INTO public.archetypes (id, name, tagline, stat_bonus, perk_description) VALUES ('class_clown', 'Class Clown (Pelawak Kelas)', 'Tukang Rusuh Positif, Pemecah Kecanggungan & Bikin Ngakak', '{"talent":2,"looks":1}'::jsonb, NULL) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, tagline = EXCLUDED.tagline, stat_bonus = EXCLUDED.stat_bonus, perk_description = EXCLUDED.perk_description;
INSERT INTO public.archetypes (id, name, tagline, stat_bonus, perk_description) VALUES ('emo', 'Emo / Serius', 'Duduk di Sudut Jendela, Headphone Terpasang & Tatapan Dingin', '{"mind":2,"intelligent":1}'::jsonb, NULL) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, tagline = EXCLUDED.tagline, stat_bonus = EXCLUDED.stat_bonus, perk_description = EXCLUDED.perk_description;
INSERT INTO public.archetypes (id, name, tagline, stat_bonus, perk_description) VALUES ('weeb', 'Weeb (Pecinta Anime / Manga / Pop Culture)', 'Chuunibyou Nyata, Gantungan Tas Penuh Pin & Imajiner Liar', '{"talent":1,"luck":2}'::jsonb, NULL) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, tagline = EXCLUDED.tagline, stat_bonus = EXCLUDED.stat_bonus, perk_description = EXCLUDED.perk_description;
INSERT INTO public.archetypes (id, name, tagline, stat_bonus, perk_description) VALUES ('popular_kids', 'Popular Kids (Idola Sekolah / Trendsetter)', 'Senyum Menawan, Pakaian Modis & Selalu Jadi Pusat Perhatian', '{"looks":2,"mind":1}'::jsonb, NULL) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, tagline = EXCLUDED.tagline, stat_bonus = EXCLUDED.stat_bonus, perk_description = EXCLUDED.perk_description;
INSERT INTO public.archetypes (id, name, tagline, stat_bonus, perk_description) VALUES ('normies', 'Normies (Murid Biasa / Kalem)', 'Tidak Banyak Tingkah, Pengamat Damai & Menghargai Hal Simpel', '{"physique":1,"intelligent":1,"looks":1,"mind":1,"talent":1,"luck":1}'::jsonb, NULL) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, tagline = EXCLUDED.tagline, stat_bonus = EXCLUDED.stat_bonus, perk_description = EXCLUDED.perk_description;

-- 4. Social Classes
INSERT INTO public.social_classes (id, name, tier, daily_allowance, initial_savings, daily_amount, savings_amount, description, starter_items) VALUES ('rich', 'Rich (Keluarga Konglomerat / Ningrat)', 'rich', '¥5,000 / Rp 500,000 per hari', '¥200,000 / Rp 20,000,000', 5000, 200000, 'Mobil pribadi siap menjemput, kartu kredit darurat, koneksi orang tua berpengaruh ke kepala sekolah.', ARRAY['Smartphone Flagship Terbaru', 'Dompet Kulit Merk Terkenal', 'Voucher Kafe Mewah', 'Kotak Pensil Impor']::TEXT[]) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, tier = EXCLUDED.tier, daily_allowance = EXCLUDED.daily_allowance, initial_savings = EXCLUDED.initial_savings, daily_amount = EXCLUDED.daily_amount, savings_amount = EXCLUDED.savings_amount, description = EXCLUDED.description, starter_items = EXCLUDED.starter_items;
INSERT INTO public.social_classes (id, name, tier, daily_allowance, initial_savings, daily_amount, savings_amount, description, starter_items) VALUES ('medium_rich', 'Medium Rich (Keluarga Menengah Atas / Dokter / Eksekutif)', 'medium_rich', '¥2,000 / Rp 200,000 per hari', '¥50,000 / Rp 5,000,000', 2000, 50000, 'Motor/skuter pribadi, sering mentraktir teman dekat, akses les privat terbaik.', ARRAY['Smartphone Bagus', 'Sepatu Branded', 'Earphone Wireless Premium', 'Tumbler Keren']::TEXT[]) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, tier = EXCLUDED.tier, daily_allowance = EXCLUDED.daily_allowance, initial_savings = EXCLUDED.initial_savings, daily_amount = EXCLUDED.daily_amount, savings_amount = EXCLUDED.savings_amount, description = EXCLUDED.description, starter_items = EXCLUDED.starter_items;
INSERT INTO public.social_classes (id, name, tier, daily_allowance, initial_savings, daily_amount, savings_amount, description, starter_items) VALUES ('medium', 'Medium (Keluarga Pegawai Biasa / Rata-rata)', 'medium', '¥1,000 / Rp 100,000 per hari', '¥15,000 / Rp 1,500,000', 1000, 15000, 'Sepeda jengki setia, kartu langganan kereta komuter, bekal makan siang enak buatan rumah.', ARRAY['Smartphone Standar', 'Kotak Bento Susun', 'Payung Lipat Polos', 'Kartu Kereta Komuter']::TEXT[]) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, tier = EXCLUDED.tier, daily_allowance = EXCLUDED.daily_allowance, initial_savings = EXCLUDED.initial_savings, daily_amount = EXCLUDED.daily_amount, savings_amount = EXCLUDED.savings_amount, description = EXCLUDED.description, starter_items = EXCLUDED.starter_items;
INSERT INTO public.social_classes (id, name, tier, daily_allowance, initial_savings, daily_amount, savings_amount, description, starter_items) VALUES ('medium_poor', 'Medium Poor (Keluarga Pas-pasan / Berhemat)', 'medium_poor', '¥500 / Rp 50,000 per hari', '¥5,000 / Rp 500,000', 500, 5000, 'Tahu toko diskon termurah di sudut kota, mandiri memasak makanan sendiri, pintar menawar.', ARRAY['Smartphone Layar Retak Sedikit', 'Botol Air Minum Isi Ulang', 'Roti Diskon Minimarket', 'Buku Catatan Murah']::TEXT[]) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, tier = EXCLUDED.tier, daily_allowance = EXCLUDED.daily_allowance, initial_savings = EXCLUDED.initial_savings, daily_amount = EXCLUDED.daily_amount, savings_amount = EXCLUDED.savings_amount, description = EXCLUDED.description, starter_items = EXCLUDED.starter_items;
INSERT INTO public.social_classes (id, name, tier, daily_allowance, initial_savings, daily_amount, savings_amount, description, starter_items) VALUES ('poor', 'Poor (Keluarga Kurang Mampu / Pejuang Hidup)', 'poor', '¥200 / Rp 20,000 per hari', '¥1,000 / Rp 100,000 (Di celengan)', 200, 1000, 'Stamina fisik luar biasa karena terbiasa kerja keras, tidak gengsian, sangat menghargai teman tulus.', ARRAY['Sepatu Kets Usang', 'Koran Bekas Pelindung Hujan', 'Nasi Kepal (Onigiri) Garam', 'Handuk Kecil Leher']::TEXT[]) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, tier = EXCLUDED.tier, daily_allowance = EXCLUDED.daily_allowance, initial_savings = EXCLUDED.initial_savings, daily_amount = EXCLUDED.daily_amount, savings_amount = EXCLUDED.savings_amount, description = EXCLUDED.description, starter_items = EXCLUDED.starter_items;
INSERT INTO public.social_classes (id, name, tier, daily_allowance, initial_savings, daily_amount, savings_amount, description, starter_items) VALUES ('orphanage', 'Orphanage (Anak Asuh Panti / Hidup Mandiri)', 'orphanage', '¥300 / Rp 30,000 per hari', '¥3,000 / Rp 300,000', 300, 3000, 'Kemandirian mutlak, rasa empati tinggi terhadap sesama orang kesepian, insting gotong royong.', ARRAY['Foto Polaroid Lama', 'Gantungan Kunci Rajut Buatan Adik Panti', 'Tas Selempang Kanvas', 'Buku Harian Rahasia']::TEXT[]) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, tier = EXCLUDED.tier, daily_allowance = EXCLUDED.daily_allowance, initial_savings = EXCLUDED.initial_savings, daily_amount = EXCLUDED.daily_amount, savings_amount = EXCLUDED.savings_amount, description = EXCLUDED.description, starter_items = EXCLUDED.starter_items;

-- 5. Equipment Packs
INSERT INTO public.equipment_packs (id, name, category, items) VALUES ('default_school_bag', 'Tas Sekolah Standar Murid', 'default', ARRAY['Buku Pelajaran & Buku Tulis Catatan', 'Kotak Pensil & Penghapus Lengkap', 'Smartphone & Earphone Kabel', 'Kartu Pelajar Sekolah', 'Payung Lipat Jaga-Jaga Hujan']::TEXT[]) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, items = EXCLUDED.items;
INSERT INTO public.equipment_packs (id, name, category, items) VALUES ('student', 'Tas Sekolah Standar Murid', 'default', ARRAY['Buku Pelajaran & Buku Tulis Catatan', 'Kotak Pensil & Penghapus Lengkap', 'Smartphone & Earphone Kabel', 'Kartu Pelajar Sekolah', 'Payung Lipat Jaga-Jaga Hujan']::TEXT[]) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, items = EXCLUDED.items;
INSERT INTO public.equipment_packs (id, name, category, items) VALUES ('club_student_council', 'Perlengkapan Klub: STUDENT COUNCIL', 'club', ARRAY['Kartu Identitas OSIS Resmi', 'Buku Agenda & Stempel OSIS', 'Walkie-Talkie Kecil Koordinasi']::TEXT[]) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, items = EXCLUDED.items;
INSERT INTO public.equipment_packs (id, name, category, items) VALUES ('club_kendo', 'Perlengkapan Klub: KENDO', 'club', ARRAY['Shinai Bambu Latihan', 'Seragam Kendogi & Hakama', 'Botol Minyak Shinai']::TEXT[]) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, items = EXCLUDED.items;
INSERT INTO public.equipment_packs (id, name, category, items) VALUES ('club_martial_arts', 'Perlengkapan Klub: MARTIAL ARTS', 'club', ARRAY['Pelindung Tangan (Karate Gloves)', 'Seragam Karate/Judo Putih', 'Perban Pergelangan Tangan']::TEXT[]) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, items = EXCLUDED.items;
INSERT INTO public.equipment_packs (id, name, category, items) VALUES ('club_sports', 'Perlengkapan Klub: SPORTS', 'club', ARRAY['Sepatu Olahraga Khusus', 'Botol Minum Sport Besar', 'Handuk Microfiber Keringat']::TEXT[]) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, items = EXCLUDED.items;
INSERT INTO public.equipment_packs (id, name, category, items) VALUES ('club_drama', 'Perlengkapan Klub: DRAMA', 'club', ARRAY['Buku Naskah Drama Bercoret-coret', 'Kotak Make-up Panggung Mini', 'Kunci Ruang Kostum']::TEXT[]) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, items = EXCLUDED.items;
INSERT INTO public.equipment_packs (id, name, category, items) VALUES ('club_kir_osn', 'Perlengkapan Klub: KIR OSN', 'club', ARRAY['Kacamata Pelindung Lab', 'Buku Catatan Eksperimen', 'Set Tabung Reaksi Kecil']::TEXT[]) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, items = EXCLUDED.items;
INSERT INTO public.equipment_packs (id, name, category, items) VALUES ('club_pramuka_paskin', 'Perlengkapan Klub: PRAMUKA PASKIN', 'club', ARRAY['Tali Pramuka 10 Meter', 'Peluit Komando', 'Kompas & Peta Sederhana']::TEXT[]) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, items = EXCLUDED.items;
INSERT INTO public.equipment_packs (id, name, category, items) VALUES ('club_pecinta_alam', 'Perlengkapan Klub: PECINTA ALAM', 'club', ARRAY['Ransel Gunung Kecil', 'Senter Kepala LED', 'Korek Api Tahan Angin']::TEXT[]) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, items = EXCLUDED.items;
INSERT INTO public.equipment_packs (id, name, category, items) VALUES ('club_penyiaran', 'Perlengkapan Klub: PENYIARAN', 'club', ARRAY['Earphone Monitor Profesional', 'Blocknote Reporter', 'Kartu Pers / ID Media Sekolah']::TEXT[]) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, items = EXCLUDED.items;
INSERT INTO public.equipment_packs (id, name, category, items) VALUES ('club_literatur', 'Perlengkapan Klub: LITERATUR', 'club', ARRAY['Buku Catatan Puisi Pribadi', 'Pena Fountain Kesayangan', 'Bookmark Kain Bordir Cantik']::TEXT[]) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, items = EXCLUDED.items;
INSERT INTO public.equipment_packs (id, name, category, items) VALUES ('club_band', 'Perlengkapan Klub: BAND', 'club', ARRAY['Pick Gitar Jimat Keberuntungan', 'Kabel Audio Pendek', 'Pelindung Telinga (Ear Plugs)']::TEXT[]) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, items = EXCLUDED.items;
INSERT INTO public.equipment_packs (id, name, category, items) VALUES ('club_painting', 'Perlengkapan Klub: PAINTING', 'club', ARRAY['Set Kuas Cat Minyak Mini', 'Buku Sketsa A5', 'Celemek Berlumur Cat Seni']::TEXT[]) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, items = EXCLUDED.items;
INSERT INTO public.equipment_packs (id, name, category, items) VALUES ('archetype_delinquent', 'Perlengkapan Arketip: DELINQUENT', 'archetype', ARRAY['Plester Luka Banyak', 'Jaket Bomber Modifikasi Keren', 'Permen Karet Mint']::TEXT[]) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, items = EXCLUDED.items;
INSERT INTO public.equipment_packs (id, name, category, items) VALUES ('archetype_jock', 'Perlengkapan Arketip: JOCK', 'archetype', ARRAY['Protein Bar / Suplemen Energi', 'Pelindung Lutut Tipis', 'Topi Olahraga Branded']::TEXT[]) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, items = EXCLUDED.items;
INSERT INTO public.equipment_packs (id, name, category, items) VALUES ('archetype_nerd', 'Perlengkapan Arketip: NERD', 'archetype', ARRAY['Kalkulator Saintifik Canggih', 'Kain Lap Kacamata Microfiber', 'Stabilo Warna-warni Lengkap']::TEXT[]) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, items = EXCLUDED.items;
INSERT INTO public.equipment_packs (id, name, category, items) VALUES ('archetype_class_clown', 'Perlengkapan Arketip: CLASS CLOWN', 'archetype', ARRAY['Sticky Note Lucu-Lucu', 'Koin Sulap Palsu', 'Buku Lelucon Kecil Tersembunyi']::TEXT[]) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, items = EXCLUDED.items;
INSERT INTO public.equipment_packs (id, name, category, items) VALUES ('archetype_emo', 'Perlengkapan Arketip: EMO', 'archetype', ARRAY['Earphone Noise-Cancelling', 'Buku Harian Terkunci', 'Gelang Karet Hitam Beberapa']::TEXT[]) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, items = EXCLUDED.items;
INSERT INTO public.equipment_packs (id, name, category, items) VALUES ('archetype_weeb', 'Perlengkapan Arketip: WEEB', 'archetype', ARRAY['Gantungan Tas Pin Anime Banyak', 'Keychain Karakter Favorit', 'Buku Manga Kecil']::TEXT[]) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, items = EXCLUDED.items;
INSERT INTO public.equipment_packs (id, name, category, items) VALUES ('archetype_popular_kids', 'Perlengkapan Arketip: POPULAR KIDS', 'archetype', ARRAY['Lipbalm / Lip Tint Mewah', 'Cermin Kompak Branded', 'Kartu Nama Murid (Custom)']::TEXT[]) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, items = EXCLUDED.items;
INSERT INTO public.equipment_packs (id, name, category, items) VALUES ('archetype_normies', 'Perlengkapan Arketip: NORMIES', 'archetype', ARRAY['Bento Box Standar', 'Botol Minum Polos', 'Pensil Cadangan (Banyak)']::TEXT[]) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, items = EXCLUDED.items;

-- 6. Basic Actions
INSERT INTO public.basic_actions (id, name, category, cost, check_type, effect, description) VALUES ('action_1', 'Pukulan Fisik (Unarmed Strike)', 'basic_combat', 'Action (Physical)', 'Physique / Power', '1 + Mod Physique (Physical Bludgeoning)', 'Tinju mentah atau tamparan spontan saat adu fisik jarak dekat.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, cost = EXCLUDED.cost, check_type = EXCLUDED.check_type, effect = EXCLUDED.effect, description = EXCLUDED.description;
INSERT INTO public.basic_actions (id, name, category, cost, check_type, effect, description) VALUES ('action_2', 'Tendangan Cepat (Snap Kick)', 'basic_combat', 'Action (Physical)', 'Physique / Agility', '1d4 + Mod Physique (Physical Bludgeoning)', 'Tendangan mendadak mengarah ke betis atau paha lawan.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, cost = EXCLUDED.cost, check_type = EXCLUDED.check_type, effect = EXCLUDED.effect, description = EXCLUDED.description;
INSERT INTO public.basic_actions (id, name, category, cost, check_type, effect, description) VALUES ('action_3', 'Dorongan Kuat (Shove)', 'basic_combat', 'Action (Physical)', 'Physique / Power vs Target Physique Save', 'Target terdorong 5 ft & mungkin terjatuh Prone', 'Mendorong lawan dengan kedua tangan penuh tenaga agar kehilangan keseimbangan.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, cost = EXCLUDED.cost, check_type = EXCLUDED.check_type, effect = EXCLUDED.effect, description = EXCLUDED.description;
INSERT INTO public.basic_actions (id, name, category, cost, check_type, effect, description) VALUES ('action_4', 'Tangkis & Bertahan (Dodge & Guard)', 'basic_combat', 'Action (Defense)', 'Otomatis', '+2 Physical & Social AC sampai giliran berikutnya', 'Memasang kuda-kuda rapat dan fokus memperhatikan gerak-gerik lawan.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, cost = EXCLUDED.cost, check_type = EXCLUDED.check_type, effect = EXCLUDED.effect, description = EXCLUDED.description;
INSERT INTO public.basic_actions (id, name, category, cost, check_type, effect, description) VALUES ('action_5', 'Kabur & Menghindar (Disengage)', 'basic_combat', 'Action (Movement)', 'Physique / Agility', 'Tidak memicu Opportunity Attack saat bergerak menjauhi lawan', 'Mundur dengan langkah cerdas memanfaatkan celah gerak lawan.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, cost = EXCLUDED.cost, check_type = EXCLUDED.check_type, effect = EXCLUDED.effect, description = EXCLUDED.description;
INSERT INTO public.basic_actions (id, name, category, cost, check_type, effect, description) VALUES ('action_6', 'Tatapan Intimidasi (Intimidating Stare)', 'basic_social', 'Action (Social Attack)', 'Looks / Aura vs Target Mind Save', '1d4 + Mod Mind (Composure Damage)', 'Menatap dengan ekspresi dingin dan intensitas yang membuat target tidak nyaman.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, cost = EXCLUDED.cost, check_type = EXCLUDED.check_type, effect = EXCLUDED.effect, description = EXCLUDED.description;
INSERT INTO public.basic_actions (id, name, category, cost, check_type, effect, description) VALUES ('action_7', 'Senyuman Persuasi (Charming Smile)', 'basic_social', 'Action (Social Attack)', 'Looks / Charm vs Target Mind Save', '1d6 + Mod Looks (Composure Damage)', 'Memberikan senyuman tulus yang membuat degup jantung target berdebar kencang.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, cost = EXCLUDED.cost, check_type = EXCLUDED.check_type, effect = EXCLUDED.effect, description = EXCLUDED.description;
INSERT INTO public.basic_actions (id, name, category, cost, check_type, effect, description) VALUES ('action_8', 'Sindiran / Provokasi (Taunt)', 'basic_social', 'Action (Social Attack)', 'Intelligent / People vs Target Mind Save', '1d4 (Composure Damage)', 'Melontarkan kata-kata tajam yang tepat sasaran untuk memancing reaksi emosional target.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, cost = EXCLUDED.cost, check_type = EXCLUDED.check_type, effect = EXCLUDED.effect, description = EXCLUDED.description;
INSERT INTO public.basic_actions (id, name, category, cost, check_type, effect, description) VALUES ('action_9', 'Rayuan Halus (Subtle Flirt)', 'basic_social', 'Action (Social Utility)', 'Looks / Charm vs Target Mind Save', '—', 'Mengirimkan sinyal halus lewat tatapan atau gestur kecil yang membuka pintu percakapan.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, cost = EXCLUDED.cost, check_type = EXCLUDED.check_type, effect = EXCLUDED.effect, description = EXCLUDED.description;
INSERT INTO public.basic_actions (id, name, category, cost, check_type, effect, description) VALUES ('action_10', 'Bantuan & Dukungan (Help / Support)', 'basic_social', 'Action (Social Utility)', 'Mind / Interpersonal', '—', 'Membantu, mendukung, atau memberikan ide kepada teman yang sedang berusaha melakukan sesuatu.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, cost = EXCLUDED.cost, check_type = EXCLUDED.check_type, effect = EXCLUDED.effect, description = EXCLUDED.description;

-- 7. Calendar Events
INSERT INTO public.calendar_events (id, term, name, event_type, description) VALUES ('cal_01', 'Semester 1 (Musim Semi)', 'Upacara Masuk & Pembagian Kelas Baru', 'school_event', 'Momen berkenalan dengan teman sebangku dan melihat siapa yang satu kelas denganmu.') ON CONFLICT (id) DO UPDATE SET term = EXCLUDED.term, name = EXCLUDED.name, event_type = EXCLUDED.event_type, description = EXCLUDED.description;
INSERT INTO public.calendar_events (id, term, name, event_type, description) VALUES ('cal_02', 'Semester 1', 'Ujian Tengah Semester (UTS / Midterms)', 'school_event', 'Pertaruhan nilai akademis, begadang kelompok belajar di perpustakaan.') ON CONFLICT (id) DO UPDATE SET term = EXCLUDED.term, name = EXCLUDED.name, event_type = EXCLUDED.event_type, description = EXCLUDED.description;
INSERT INTO public.calendar_events (id, term, name, event_type, description) VALUES ('cal_03', 'Semester 1', 'Festival Olahraga (Undoukai)', 'school_event', 'Lari estafet, tarik tambang, dan kesempatan menyemangati gebetan dari pinggir lapangan.') ON CONFLICT (id) DO UPDATE SET term = EXCLUDED.term, name = EXCLUDED.name, event_type = EXCLUDED.event_type, description = EXCLUDED.description;
INSERT INTO public.calendar_events (id, term, name, event_type, description) VALUES ('cal_04', 'Liburan Semester 1', 'Liburan Musim Panas & Festival Kembang Api', 'school_event', 'Mengenakan pakaian Yukata, janjian nonton kembang api kuil di malam hari.') ON CONFLICT (id) DO UPDATE SET term = EXCLUDED.term, name = EXCLUDED.name, event_type = EXCLUDED.event_type, description = EXCLUDED.description;
INSERT INTO public.calendar_events (id, term, name, event_type, description) VALUES ('cal_05', 'Semester 2 (Musim Gugur)', 'Festival Budaya Sekolah (Bunkasai)', 'school_event', 'Acara puncak tahunan! Rumah hantu, maid cafe kelas, dan konser band panggung sekolah.') ON CONFLICT (id) DO UPDATE SET term = EXCLUDED.term, name = EXCLUDED.name, event_type = EXCLUDED.event_type, description = EXCLUDED.description;
INSERT INTO public.calendar_events (id, term, name, event_type, description) VALUES ('cal_06', 'Semester 2', 'Study Tour Sekolah (Shuugakuryokou)', 'school_event', 'Perjalanan bus menginap ke Kyoto/daerah wisata; curhat rahasia malam hari di kamar hotel.') ON CONFLICT (id) DO UPDATE SET term = EXCLUDED.term, name = EXCLUDED.name, event_type = EXCLUDED.event_type, description = EXCLUDED.description;
INSERT INTO public.calendar_events (id, term, name, event_type, description) VALUES ('cal_07', 'Semester 2 (Musim Dingin)', 'Hari Valentine & White Day', 'school_event', 'Menaruh cokelat honmei (cinta tulus) atau giri (pertemanan) di dalam loker sepatu.') ON CONFLICT (id) DO UPDATE SET term = EXCLUDED.term, name = EXCLUDED.name, event_type = EXCLUDED.event_type, description = EXCLUDED.description;
INSERT INTO public.calendar_events (id, term, name, event_type, description) VALUES ('cal_08', 'Akhir Tahun Ajaran', 'Ujian Kenaikan Kelas & Upacara Kelulusan', 'school_event', 'Pengumuman kelulusan dan momen perpisahan yang penuh air mata kenangan.') ON CONFLICT (id) DO UPDATE SET term = EXCLUDED.term, name = EXCLUDED.name, event_type = EXCLUDED.event_type, description = EXCLUDED.description;
