-- ============================================================================
-- Migration: 20261007000003_seed_compendium.sql
-- Description: Seed master compendium data from DD_DATA
-- ============================================================================

-- 1. Abilities & Skills
INSERT INTO public.abilities (id, name, short_code, dnd_equiv, description) VALUES ('physique', 'Physique', 'PHY', 'STR / DEX / CON', 'Kekuatan otot, kelenturan tubuh, refleks motorik, dan daya tahan fisik.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, short_code = EXCLUDED.short_code, dnd_equiv = EXCLUDED.dnd_equiv, description = EXCLUDED.description;
INSERT INTO public.skills (id, ability_id, name, description) VALUES ('power', 'physique', 'Power', 'Angkat beban, mendobrak pintu, memukul, mendorong, dan adu tenaga fisik.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description;
INSERT INTO public.skills (id, ability_id, name, description) VALUES ('agility', 'physique', 'Agility', 'Kelincahan, kecepatan refleks, kejar kereta, panjat pagar sekolah, dan kelenturan.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description;
INSERT INTO public.skills (id, ability_id, name, description) VALUES ('stamina', 'physique', 'Stamina', 'Daya tahan lari maraton, begadang belajar, tahan benturan, dan tidak mudah masuk angin.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description;
INSERT INTO public.abilities (id, name, short_code, dnd_equiv, description) VALUES ('intelligent', 'Intelligent', 'INT', 'INT / Logic', 'Kecerdasan akademis, nalar logika, pemecahan masalah, dan pengetahuan jalanan.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, short_code = EXCLUDED.short_code, dnd_equiv = EXCLUDED.dnd_equiv, description = EXCLUDED.description;
INSERT INTO public.skills (id, ability_id, name, description) VALUES ('academic', 'intelligent', 'Academic', 'Materi ujian sekolah, rumus matematika/sains, sejarah, dan hafalan teori pelajaran.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description;
INSERT INTO public.skills (id, ability_id, name, description) VALUES ('people', 'intelligent', 'People', 'Membaca psikologi lawan, menganalisis bahasa tubuh, mendeteksi motif bohong/salting.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description;
INSERT INTO public.skills (id, ability_id, name, description) VALUES ('street', 'intelligent', 'Street', 'Akal-akalan pergaulan, tahu jalan pintas rahasia kota, gosip geng, dan trik bertahan di jalanan.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description;
INSERT INTO public.abilities (id, name, short_code, dnd_equiv, description) VALUES ('looks', 'Looks', 'LOK', 'CHA / Attractiveness', 'Daya tarik visual, pesona karismatik, gaya berpakaian, dan aura kehadiran.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, short_code = EXCLUDED.short_code, dnd_equiv = EXCLUDED.dnd_equiv, description = EXCLUDED.description;
INSERT INTO public.skills (id, ability_id, name, description) VALUES ('charm', 'looks', 'Charm', 'Pesona personal, senyuman menawan, rayuan asmara, kedipan mata, dan daya pikat alami.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description;
INSERT INTO public.skills (id, ability_id, name, description) VALUES ('influence', 'looks', 'Influence', 'Pengaruh reputasi di kalangan murid, disegani kawan dan lawan, serta wibawa status.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description;
INSERT INTO public.skills (id, ability_id, name, description) VALUES ('aura', 'looks', 'Aura', 'Kehadiran yang mencolok, tatapan tajam berkarisma, atau vibes misterius yang membius.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description;
INSERT INTO public.abilities (id, name, short_code, dnd_equiv, description) VALUES ('mind', 'Mind', 'MND', 'WIS / Mental Fortitude', 'Kekuatan mental, ketenangan batin, empati, dan kepekaan membaca atmosfer sekitar.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, short_code = EXCLUDED.short_code, dnd_equiv = EXCLUDED.dnd_equiv, description = EXCLUDED.description;
INSERT INTO public.skills (id, ability_id, name, description) VALUES ('emotional', 'mind', 'Emotional', 'Kontrol emosi pribadi, jaga imej (jaim), menahan rasa malu, dan mengelola kegelisahan hati.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description;
INSERT INTO public.skills (id, ability_id, name, description) VALUES ('interpersonal', 'mind', 'Interpersonal', 'Peka terhadap perasaan orang lain, mendengarkan curhat, merajut ikatan hati mendalam.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description;
INSERT INTO public.skills (id, ability_id, name, description) VALUES ('awareness', 'mind', 'Awareness', 'Membaca atmosfer sosial (Kuuki Yomenai / Kuuki Yomeru), menyadari tatapan rahasia orang lain.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description;
INSERT INTO public.abilities (id, name, short_code, dnd_equiv, description) VALUES ('talent', 'Talent', 'TLN', 'Performance / Creativity', 'Bakat alami, ekspresi kesenian, keahlian panggung, dan keluwesan berimprovisasi.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, short_code = EXCLUDED.short_code, dnd_equiv = EXCLUDED.dnd_equiv, description = EXCLUDED.description;
INSERT INTO public.skills (id, ability_id, name, description) VALUES ('creative', 'talent', 'Creative', 'Merancang ide festival sekolah, menulis surat cinta puitis, ilustrasi, dan desain kreatif.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description;
INSERT INTO public.skills (id, ability_id, name, description) VALUES ('performance', 'talent', 'Performance', 'Akting panggung drama, bernyanyi, memainkan instrumen musik, dan pidato membakar semangat.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description;
INSERT INTO public.skills (id, ability_id, name, description) VALUES ('adaptability', 'talent', 'Adaptability', 'Improvisasi kilat saat rencana berantakan, mengubah suasana kaku, dan fleksibel menghadapi situasi.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description;
INSERT INTO public.abilities (id, name, short_code, dnd_equiv, description) VALUES ('luck', 'Luck', 'LCK', 'Fate / Fortune', 'Faktor keberuntungan murni, takdir kasmaran, dan kebetulan-kebetulan dramatis anime.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, short_code = EXCLUDED.short_code, dnd_equiv = EXCLUDED.dnd_equiv, description = EXCLUDED.description;
INSERT INTO public.skills (id, ability_id, name, description) VALUES ('relationship_luck', 'luck', 'Relationship Luck', 'Papasan romantis tidak sengaja, tabrakan bawa roti di tikungan, terlindung payung bareng saat hujan.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description;
INSERT INTO public.skills (id, ability_id, name, description) VALUES ('situation_luck', 'luck', 'Situation Luck', 'Lolos razia sidak guru BP, nemu uang di jalan, guru killer izin tidak masuk kelas.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description;
INSERT INTO public.skills (id, ability_id, name, description) VALUES ('academic_luck', 'luck', 'Academic Luck', 'Hoki tebak kancing saat ujian, materi yang dipelajari semalam pas keluar di lembar soal.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description;

-- 2. Ekskul (Classes), Subclasses, and Club Moves
INSERT INTO public.ekskul (id, name, tagline, hit_die, primary_stat, saving_throws, perk_description) VALUES ('student_council', 'Student Council (OSIS)', 'Elit Organisasi & Penegak Ketertiban Sekolah', 'd8', 'Looks / Intelligent', ARRAY['intelligent', 'looks']::TEXT[], 'Hak akses ruang OSIS ber-AC, wewenang menegur murid lain, anggaran proposal kegiatan sekolah, dan disegani dewan guru.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, tagline = EXCLUDED.tagline, hit_die = EXCLUDED.hit_die, primary_stat = EXCLUDED.primary_stat, saving_throws = EXCLUDED.saving_throws, perk_description = EXCLUDED.perk_description;
INSERT INTO public.ekskul_subclasses (id, ekskul_id, name, description) VALUES ('presidium', 'student_council', 'Ketua / Presidium', 'Pemimpin mutlak OSIS. Bonus +2 pada semua Looks checks saat berhadapan dengan guru atau undangan eksternal.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description;
INSERT INTO public.ekskul_subclasses (id, ekskul_id, name, description) VALUES ('discipline', 'student_council', 'Divisi Kedisiplinan', 'Penegak aturan sekolah. Advantage pada Intimidasi dan Check untuk mendeteksi pelanggaran murid lain.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description;
INSERT INTO public.ekskul_moves (id, ekskul_id, name, move_type, cost, range, check_type, effect, description) VALUES ('student_council_move_1', 'student_council', 'Perintah Kedisiplinan (Disciplinary Order)', 'Social Move', '1 Action', '30 ft', 'Looks / Influence', 'Target Mind Save (DC 8+Prof+Looks). Gagal: Stunned 1 giliran & kehilangan 1d6 Composure.', 'Menegur target dengan suara tegas berwibawa khas OSIS.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, move_type = EXCLUDED.move_type, cost = EXCLUDED.cost, range = EXCLUDED.range, check_type = EXCLUDED.check_type, effect = EXCLUDED.effect, description = EXCLUDED.description;
INSERT INTO public.ekskul_moves (id, ekskul_id, name, move_type, cost, range, check_type, effect, description) VALUES ('student_council_move_2', 'student_council', 'Koneksi Pihak Sekolah (Faculty Pass)', 'Reaction / Utility', '1x per Short Rest', 'Self / Touch', 'Otomatis', 'Membatalkan konsekuensi teguran guru atau razia loker untuk dirimu dan 1 teman.', 'Menunjukkan kartu identitas OSIS atau surat tugas resmi.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, move_type = EXCLUDED.move_type, cost = EXCLUDED.cost, range = EXCLUDED.range, check_type = EXCLUDED.check_type, effect = EXCLUDED.effect, description = EXCLUDED.description;
INSERT INTO public.ekskul_moves (id, ekskul_id, name, move_type, cost, range, check_type, effect, description) VALUES ('student_council_move_3', 'student_council', 'Proposal Darurat (Emergency Budget)', 'Utility Move', '10 Menit', 'Self', 'Intelligent / Academic', 'Mendapatkan 1 item kebutuhan mendesak (alat sekolah, tiket, pass) tanpa biaya selama sesi ini.', 'Menyusun surat permintaan dana darurat dengan stempel OSIS resmi.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, move_type = EXCLUDED.move_type, cost = EXCLUDED.cost, range = EXCLUDED.range, check_type = EXCLUDED.check_type, effect = EXCLUDED.effect, description = EXCLUDED.description;
INSERT INTO public.ekskul (id, name, tagline, hit_die, primary_stat, saving_throws, perk_description) VALUES ('kendo', 'Kendo (Pedang Bambu)', 'Disiplin Pedang Samurai & Konsentrasi Batin', 'd10', 'Physique / Mind', ARRAY['physique', 'mind']::TEXT[], 'Penguasaan teknik Shinai dan Bokken, ruang latihan Dojo tradisional, kuda-kuda kokoh, dan fokus mata yang tak goyah.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, tagline = EXCLUDED.tagline, hit_die = EXCLUDED.hit_die, primary_stat = EXCLUDED.primary_stat, saving_throws = EXCLUDED.saving_throws, perk_description = EXCLUDED.perk_description;
INSERT INTO public.ekskul_subclasses (id, ekskul_id, name, description) VALUES ('men_striker', 'kendo', 'Gaya Serangan Kilat (Men-Striker)', 'Spesialisasi serangan cepat. Bonus aksi ekstra setelah serangan sukses pertama dalam ronde.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description;
INSERT INTO public.ekskul_subclasses (id, ekskul_id, name, description) VALUES ('iron_guard', 'kendo', 'Gaya Pertahanan Keras (Iron Wall)', 'Spesialisasi pertahanan. +1 Physical AC permanen dan Advantage pada Physique Saving Throw.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description;
INSERT INTO public.ekskul_moves (id, ekskul_id, name, move_type, cost, range, check_type, effect, description) VALUES ('kendo_move_1', 'kendo', 'Tebasan Shinai: Men! (Head Slash)', 'Attack / Club Move', '1 Action', 'Melee (5 ft)', 'Physique / Power', '1d8 + Mod Physique Bludgeoning. Jika mengenai helm/kepala: target Physique Save atau Disadvantage serangan berikutnya.', 'Pukulan vertikal terarah ke arah kepala dengan teriakan kiai menggelegar.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, move_type = EXCLUDED.move_type, cost = EXCLUDED.cost, range = EXCLUDED.range, check_type = EXCLUDED.check_type, effect = EXCLUDED.effect, description = EXCLUDED.description;
INSERT INTO public.ekskul_moves (id, ekskul_id, name, move_type, cost, range, check_type, effect, description) VALUES ('kendo_move_2', 'kendo', 'Tangkisan Sempurna (Kendo Parry)', 'Reaction', 'Reaction', 'Self', '+2 Physical AC', 'Menambah +2 Physical AC terhadap 1 serangan fisik jarak dekat yang terlihat.', 'Mengayunkan pedang bambu membentuk sudut tangkisan tajam membelokkan serangan lawan.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, move_type = EXCLUDED.move_type, cost = EXCLUDED.cost, range = EXCLUDED.range, check_type = EXCLUDED.check_type, effect = EXCLUDED.effect, description = EXCLUDED.description;
INSERT INTO public.ekskul_moves (id, ekskul_id, name, move_type, cost, range, check_type, effect, description) VALUES ('kendo_move_3', 'kendo', 'Kiai: Teriakan Semangat (Kiai Shout)', 'Bonus Action / Buff', '1 Bonus Action', '30 ft', 'Mind / Emotional', 'Dirimu dan 1 sekutu mendapat Advantage pada serangan fisik berikutnya di ronde ini.', 'Melepas teriakan kiai penuh konsentrasi yang membakar semangat tempur.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, move_type = EXCLUDED.move_type, cost = EXCLUDED.cost, range = EXCLUDED.range, check_type = EXCLUDED.check_type, effect = EXCLUDED.effect, description = EXCLUDED.description;
INSERT INTO public.ekskul (id, name, tagline, hit_die, primary_stat, saving_throws, perk_description) VALUES ('martial_arts', 'Martial Arts (Beladiri / Karate / Judo)', 'Pertarungan Jarak Dekat & Refleks Bantingan', 'd10', 'Physique', ARRAY['physique', 'talent']::TEXT[], 'Tubuh liat tahan banting, pukulan dan tendangan tanpa senjata berdaya hancur tinggi, serta kemampuan melumpuhkan lawan tanpa senjata tajam.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, tagline = EXCLUDED.tagline, hit_die = EXCLUDED.hit_die, primary_stat = EXCLUDED.primary_stat, saving_throws = EXCLUDED.saving_throws, perk_description = EXCLUDED.perk_description;
INSERT INTO public.ekskul_subclasses (id, ekskul_id, name, description) VALUES ('grappler', 'martial_arts', 'Spesialis Bantingan (Judo / Grappler)', 'Ahli merebut dan membanting lawan ke tanah. Serangan Bantingan memberikan +2d4 damage tambahan.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description;
INSERT INTO public.ekskul_subclasses (id, ekskul_id, name, description) VALUES ('striker', 'martial_arts', 'Spesialis Serangan Beruntun (Striker)', 'Ahli combo pukulan cepat. Bisa menyerang 2 kali dengan 1 aksi (setelah level 3+).') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description;
INSERT INTO public.ekskul_moves (id, ekskul_id, name, move_type, cost, range, check_type, effect, description) VALUES ('martial_arts_move_1', 'martial_arts', 'Bantingan Matras (Seoi-Nage Takedown)', 'Attack / Club Move', '1 Action', 'Melee (5 ft)', 'Physique / Power vs Target Physique Save', '1d6 + Mod Physique Bludgeoning. Target terjatuh Prone (terkapar).', 'Menarik kerah atau lengan lawan, memutar badan, dan membantingnya keras ke lantai.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, move_type = EXCLUDED.move_type, cost = EXCLUDED.cost, range = EXCLUDED.range, check_type = EXCLUDED.check_type, effect = EXCLUDED.effect, description = EXCLUDED.description;
INSERT INTO public.ekskul_moves (id, ekskul_id, name, move_type, cost, range, check_type, effect, description) VALUES ('martial_arts_move_2', 'martial_arts', 'Pukulan Cepat Kombo (Rapid Flurry)', 'Bonus Action', '1 Bonus Action', 'Melee (5 ft)', 'Physique / Agility', '1d4 + Mod Physique Physical Damage tambahan setelah serangan utama.', 'Kombinasi pukulan cepat tanpa jeda menyasar perut lawan.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, move_type = EXCLUDED.move_type, cost = EXCLUDED.cost, range = EXCLUDED.range, check_type = EXCLUDED.check_type, effect = EXCLUDED.effect, description = EXCLUDED.description;
INSERT INTO public.ekskul_moves (id, ekskul_id, name, move_type, cost, range, check_type, effect, description) VALUES ('martial_arts_move_3', 'martial_arts', 'Kunci Sendi (Joint Lock)', 'Attack / Club Move', '1 Action', 'Melee (5 ft)', 'Physique / Agility vs Target Physique Save', 'Target Restrained selama 1 giliran. Target tidak bisa menyerang hingga lolos dengan Physique check DC 12.', 'Memegang siku atau pergelangan tangan lawan dan menguncinya ke sudut yang menyakitkan.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, move_type = EXCLUDED.move_type, cost = EXCLUDED.cost, range = EXCLUDED.range, check_type = EXCLUDED.check_type, effect = EXCLUDED.effect, description = EXCLUDED.description;
INSERT INTO public.ekskul (id, name, tagline, hit_die, primary_stat, saving_throws, perk_description) VALUES ('sports', 'Sports (Sepak Bola / Basket / Atletik)', 'Stamina Baja & Kecepatan Lapangan Terbuka', 'd10', 'Physique / Looks', ARRAY['physique', 'physique']::TEXT[], 'Kecepatan lari di atas rata-rata (+10 ft speed), keringat karismatik yang digemari murid lain, dan stamina tahan maraton.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, tagline = EXCLUDED.tagline, hit_die = EXCLUDED.hit_die, primary_stat = EXCLUDED.primary_stat, saving_throws = EXCLUDED.saving_throws, perk_description = EXCLUDED.perk_description;
INSERT INTO public.ekskul_subclasses (id, ekskul_id, name, description) VALUES ('ace_striker', 'sports', 'Striker / Ace Lapangan', 'Serangan fisik berbasis kecepatan. Bonus +1d4 damage saat menyerang setelah berlari setidaknya 15 ft.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description;
INSERT INTO public.ekskul_subclasses (id, ekskul_id, name, description) VALUES ('team_captain', 'sports', 'Kapten Regu', 'Pemimpin tim. Sekali per istirahat, berikan 1d6 Inspiration Die ke seluruh anggota tim.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description;
INSERT INTO public.ekskul_moves (id, ekskul_id, name, move_type, cost, range, check_type, effect, description) VALUES ('sports_move_1', 'sports', 'Terobosan Kilat (Fast Break Sprint)', 'Bonus Action', '1 Bonus Action', 'Self', 'Otomatis', 'Menggandakan kecepatan gerak (Dash) dan tidak memicu Opportunity Attack saat bergerak melewati lawan.', 'Manuver lari cepat zig-zag menembus kerumunan seperti mengejar bola di lapangan.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, move_type = EXCLUDED.move_type, cost = EXCLUDED.cost, range = EXCLUDED.range, check_type = EXCLUDED.check_type, effect = EXCLUDED.effect, description = EXCLUDED.description;
INSERT INTO public.ekskul_moves (id, ekskul_id, name, move_type, cost, range, check_type, effect, description) VALUES ('sports_move_2', 'sports', 'Lemparan Bola Akurat (Precision Throw)', 'Attack / Club Move', '1 Action', 'Ranged (40 ft)', 'Physique / Agility', '1d6 + Mod Physique Bludgeoning. Target terpental atau terkejut jika kena di wajah.', 'Melempar bola basket, bola voli, atau benda bulat lainnya dengan ketepatan presisi tinggi.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, move_type = EXCLUDED.move_type, cost = EXCLUDED.cost, range = EXCLUDED.range, check_type = EXCLUDED.check_type, effect = EXCLUDED.effect, description = EXCLUDED.description;
INSERT INTO public.ekskul_moves (id, ekskul_id, name, move_type, cost, range, check_type, effect, description) VALUES ('sports_move_3', 'sports', 'Sorak Penyemangat (Rally Cheer)', 'Buff Move', 'Bonus Action', '30 ft', 'Looks / Influence', '1 sekutu memulihkan 1d4 Physical HP dan mendapat Advantage pada 1 check fisik berikutnya.', 'Berteriak penuh semangat ke arah teman yang tertekan, memicu adrenalin mereka kembali.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, move_type = EXCLUDED.move_type, cost = EXCLUDED.cost, range = EXCLUDED.range, check_type = EXCLUDED.check_type, effect = EXCLUDED.effect, description = EXCLUDED.description;
INSERT INTO public.ekskul (id, name, tagline, hit_die, primary_stat, saving_throws, perk_description) VALUES ('drama', 'Drama Club (Teater & Seni Peran)', 'Manipulasi Emosi, Akting Panggung & Dusta Sempurna', 'd8', 'Looks / Talent', ARRAY['looks', 'talent']::TEXT[], 'Kostum panggung beragam, kemampuan meneteskan air mata buatan seketika, menirukan intonasi orang lain, dan menyamar.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, tagline = EXCLUDED.tagline, hit_die = EXCLUDED.hit_die, primary_stat = EXCLUDED.primary_stat, saving_throws = EXCLUDED.saving_throws, perk_description = EXCLUDED.perk_description;
INSERT INTO public.ekskul_subclasses (id, ekskul_id, name, description) VALUES ('lead_actor', 'drama', 'Aktor Protagonis / Bintang Panggung', 'Ahli menarik simpati massa. Serangan sosial berbasis Looks memberikan 1d4 bonus damage Composure.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description;
INSERT INTO public.ekskul_subclasses (id, ekskul_id, name, description) VALUES ('antagonist', 'drama', 'Master Tipu Daya (Antagonist)', 'Ahli manipulasi. Advantage pada semua check untuk menipu, berpura-pura, atau menyamar.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description;
INSERT INTO public.ekskul_moves (id, ekskul_id, name, move_type, cost, range, check_type, effect, description) VALUES ('drama_move_1', 'drama', 'Air Mata Buatan (Fake Tears / Manipulation)', 'Social Move', '1 Action', '15 ft', 'Talent / Performance vs Target Mind Save', 'Target Disadvantage semua serangan terhadapmu & kehilangan 1d6 Composure karena rasa bersalah.', 'Berakting sedih tersedu-sedu sambil menggigit bibir, membalikkan simpati seluruh orang di sekitar.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, move_type = EXCLUDED.move_type, cost = EXCLUDED.cost, range = EXCLUDED.range, check_type = EXCLUDED.check_type, effect = EXCLUDED.effect, description = EXCLUDED.description;
INSERT INTO public.ekskul_moves (id, ekskul_id, name, move_type, cost, range, check_type, effect, description) VALUES ('drama_move_2', 'drama', 'Persona Penyamaran (Method Acting)', 'Utility Move', '10 Menit', 'Self', 'Talent / Adaptability', 'Advantage pada semua check People & Street saat menyamar sebagai tipe orang lain.', 'Merombak gaya bicara, cara jalan, dan dandanan untuk berpura-pura jadi murid lain.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, move_type = EXCLUDED.move_type, cost = EXCLUDED.cost, range = EXCLUDED.range, check_type = EXCLUDED.check_type, effect = EXCLUDED.effect, description = EXCLUDED.description;
INSERT INTO public.ekskul_moves (id, ekskul_id, name, move_type, cost, range, check_type, effect, description) VALUES ('drama_move_3', 'drama', 'Monolog Dramatis (Grand Speech)', 'Social Move', '1 Action', '30 ft (Area)', 'Talent / Performance vs seluruh target Mind Save', 'Seluruh musuh dalam jangkauan kehilangan 1d4 Composure. Sekutu mendapat Advantage pada Social Saves 1 giliran.', 'Berpidato dengan ekspresi dramatis penuh penjiwaan yang menguras emosi siapa saja yang mendengar.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, move_type = EXCLUDED.move_type, cost = EXCLUDED.cost, range = EXCLUDED.range, check_type = EXCLUDED.check_type, effect = EXCLUDED.effect, description = EXCLUDED.description;
INSERT INTO public.ekskul (id, name, tagline, hit_die, primary_stat, saving_throws, perk_description) VALUES ('kir_osn', 'KIR / OSN (Sains & Karya Ilmiah Remaja)', 'Analisis Tajam, Riset Ilmiah & Reaksi Kimia', 'd6', 'Intelligent', ARRAY['intelligent', 'mind']::TEXT[], 'Kunci akses laboratorium sains & bahan kimia, bank soal olimpiade, mikroskop, dan laptop penuh data analisis.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, tagline = EXCLUDED.tagline, hit_die = EXCLUDED.hit_die, primary_stat = EXCLUDED.primary_stat, saving_throws = EXCLUDED.saving_throws, perk_description = EXCLUDED.perk_description;
INSERT INTO public.ekskul_subclasses (id, ekskul_id, name, description) VALUES ('chemist', 'kir_osn', 'Peneliti Kimia & Biologi', 'Ahli senyawa kimia. Bisa menciptakan efek racun, asap, atau pelemas otot dari bahan lab sekali per sesi.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description;
INSERT INTO public.ekskul_subclasses (id, ekskul_id, name, description) VALUES ('hacker', 'kir_osn', 'Hacker Komputer & Robotika', 'Ahli perangkat digital. Advantage pada check Intelligent untuk membobol sistem, CCTV, atau kunci digital.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description;
INSERT INTO public.ekskul_moves (id, ekskul_id, name, move_type, cost, range, check_type, effect, description) VALUES ('kir_osn_move_1', 'kir_osn', 'Analisis Titik Lemah (Analytical Deduction)', 'Bonus Action', '1 Bonus Action', '30 ft', 'Intelligent / Academic', 'Mengetahui 1 stat tertinggi dan 1 kelemahan target. Serangan sekutu berikutnya ke target mendapat Advantage.', 'Mengamati postur dan kebiasaan lawan lewat perhitungan matematis untuk menemukan celah pertahanan.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, move_type = EXCLUDED.move_type, cost = EXCLUDED.cost, range = EXCLUDED.range, check_type = EXCLUDED.check_type, effect = EXCLUDED.effect, description = EXCLUDED.description;
INSERT INTO public.ekskul_moves (id, ekskul_id, name, move_type, cost, range, check_type, effect, description) VALUES ('kir_osn_move_2', 'kir_osn', 'Asap Reaksi Kimia (Lab Smoke Screen)', 'Utility / Combat Move', '1 Action', '15 ft', 'Otomatis', 'Menciptakan kabut pekat radius 10 ft selama 2 giliran. Semua pandangan di dalamnya tertutup.', 'Mencampurkan larutan kimia darurat dari tabung saku menghasilkan asap tebal.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, move_type = EXCLUDED.move_type, cost = EXCLUDED.cost, range = EXCLUDED.range, check_type = EXCLUDED.check_type, effect = EXCLUDED.effect, description = EXCLUDED.description;
INSERT INTO public.ekskul_moves (id, ekskul_id, name, move_type, cost, range, check_type, effect, description) VALUES ('kir_osn_move_3', 'kir_osn', 'Formula Konsentrasi (Study Buff)', 'Utility Move', '10 Menit', 'Self / Touch', 'Intelligent / Academic', 'Target mendapat Advantage pada 1 check Intelligent atau Talent berikutnya dalam 1 jam ke depan.', 'Menyusun peta konsep atau ringkasan materi kilat agar pikiran fokus sebelum tes atau debat.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, move_type = EXCLUDED.move_type, cost = EXCLUDED.cost, range = EXCLUDED.range, check_type = EXCLUDED.check_type, effect = EXCLUDED.effect, description = EXCLUDED.description;
INSERT INTO public.ekskul (id, name, tagline, hit_die, primary_stat, saving_throws, perk_description) VALUES ('pramuka_paskin', 'Pramuka / Paskin (Paskibra & Kedisiplinan Baris)', 'Tali Temali, Disiplin Militer & Postur Tegak', 'd10', 'Physique / Mind', ARRAY['physique', 'mind']::TEXT[], 'Keahlian tali temali mengikat barang/lawan, tiang bendera serbaguna, peluit komando, dan daya tahan berjemur di lapangan.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, tagline = EXCLUDED.tagline, hit_die = EXCLUDED.hit_die, primary_stat = EXCLUDED.primary_stat, saving_throws = EXCLUDED.saving_throws, perk_description = EXCLUDED.perk_description;
INSERT INTO public.ekskul_subclasses (id, ekskul_id, name, description) VALUES ('danton', 'pramuka_paskin', 'Komandan Peleton (Danton)', 'Pemimpin barisan. Advantage saat memimpin aksi kelompok, bonus +2 pada semua Social Saves tim.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description;
INSERT INTO public.ekskul_subclasses (id, ekskul_id, name, description) VALUES ('pioneer', 'pramuka_paskin', 'Pionir Tali Temali & Tenda', 'Ahli bertahan hidup. Tidak pernah kehilangan arah di luar ruangan. +2 Physique Save terhadap bahaya alam.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description;
INSERT INTO public.ekskul_moves (id, ekskul_id, name, move_type, cost, range, check_type, effect, description) VALUES ('pramuka_paskin_move_1', 'pramuka_paskin', 'Kuncian Tali Pramuka (Rope Restrain)', 'Attack / Club Move', '1 Action', 'Melee (5 ft)', 'Physique / Agility vs Target Agility', 'Target Restrained tidak bisa bergerak hingga lolos Physique check DC 13.', 'Menggunakan seutas tali pramuka tebal untuk membelenggu tangan atau kaki lawan.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, move_type = EXCLUDED.move_type, cost = EXCLUDED.cost, range = EXCLUDED.range, check_type = EXCLUDED.check_type, effect = EXCLUDED.effect, description = EXCLUDED.description;
INSERT INTO public.ekskul_moves (id, ekskul_id, name, move_type, cost, range, check_type, effect, description) VALUES ('pramuka_paskin_move_2', 'pramuka_paskin', 'Aba-aba Menggelegar (Commanding Drill)', 'Buff / Social Move', '1 Bonus Action', '30 ft', 'Mind / Emotional', 'Semua kawan dalam radius 30 ft mendapat +2 bonus pada Saving Throw berikutnya.', 'Meneriakkan aba-aba baris berbaris dengan nada tegas yang membangkitkan fokus kawan.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, move_type = EXCLUDED.move_type, cost = EXCLUDED.cost, range = EXCLUDED.range, check_type = EXCLUDED.check_type, effect = EXCLUDED.effect, description = EXCLUDED.description;
INSERT INTO public.ekskul_moves (id, ekskul_id, name, move_type, cost, range, check_type, effect, description) VALUES ('pramuka_paskin_move_3', 'pramuka_paskin', 'Teknik Pengintaian (Scout Surveillance)', 'Utility Move', '1 Menit', '60 ft', 'Mind / Awareness', 'Mendeteksi jumlah dan posisi semua musuh atau target di area dalam jangkauan selama 1 menit.', 'Mengamati lingkungan sekitar dengan gerakan senyap dan sistematis layaknya pengintai lapangan.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, move_type = EXCLUDED.move_type, cost = EXCLUDED.cost, range = EXCLUDED.range, check_type = EXCLUDED.check_type, effect = EXCLUDED.effect, description = EXCLUDED.description;
INSERT INTO public.ekskul (id, name, tagline, hit_die, primary_stat, saving_throws, perk_description) VALUES ('pecinta_alam', 'Pecinta Alam (Mapala / Sispala)', 'Insting Bertahan Hidup, Peta Liar & Fisik Tangguh', 'd10', 'Physique / Mind', ARRAY['physique', 'mind']::TEXT[], 'Tenda dome portabel, kompor gas mini, ransel gunung besar (kapasitas tas ekstra), dan indra penciuman cuaca tajam.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, tagline = EXCLUDED.tagline, hit_die = EXCLUDED.hit_die, primary_stat = EXCLUDED.primary_stat, saving_throws = EXCLUDED.saving_throws, perk_description = EXCLUDED.perk_description;
INSERT INTO public.ekskul_subclasses (id, ekskul_id, name, description) VALUES ('explorer', 'pecinta_alam', 'Penjelajah Rimba & Pendaki', 'Spesialis navigasi dan terrain. Advantage pada Physique checks untuk memanjat, berenang, atau melintasi rintangan alam.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description;
INSERT INTO public.ekskul_subclasses (id, ekskul_id, name, description) VALUES ('medic', 'pecinta_alam', 'Ahli Pertolongan Pertama (Medic)', 'Spesialis penyembuhan lapangan. Heal dice meningkat jadi 1d10 dan bisa menyembuhkan 1 teman per Short Rest.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description;
INSERT INTO public.ekskul_moves (id, ekskul_id, name, move_type, cost, range, check_type, effect, description) VALUES ('pecinta_alam_move_1', 'pecinta_alam', 'Insting Survival (Wilderness Awareness)', 'Pasif / Reaksi', 'Pasif / Reaksi', 'Self', 'Mind / Awareness', 'Tidak pernah tersesat di area luar ruangan dan tidak bisa dikejutkan (Surprised) dalam bahaya mendadak.', 'Membaca arah angin, lumut pohon, dan jejak langkah kaki di tanah.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, move_type = EXCLUDED.move_type, cost = EXCLUDED.cost, range = EXCLUDED.range, check_type = EXCLUDED.check_type, effect = EXCLUDED.effect, description = EXCLUDED.description;
INSERT INTO public.ekskul_moves (id, ekskul_id, name, move_type, cost, range, check_type, effect, description) VALUES ('pecinta_alam_move_2', 'pecinta_alam', 'P3K Darurat Lapangan (First Aid Field Patch)', 'Heal Move', '1 Action (1x per Rest)', 'Touch', 'Otomatis', 'Memulihkan 1d8 + Mod Mind Physical HP atau Composure ke teman yang terluka.', 'Membalut luka dengan perban elastis dan memberikan air minum hangat dari termos lapangan.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, move_type = EXCLUDED.move_type, cost = EXCLUDED.cost, range = EXCLUDED.range, check_type = EXCLUDED.check_type, effect = EXCLUDED.effect, description = EXCLUDED.description;
INSERT INTO public.ekskul_moves (id, ekskul_id, name, move_type, cost, range, check_type, effect, description) VALUES ('pecinta_alam_move_3', 'pecinta_alam', 'Panjat Penghalang (Obstacle Climb)', 'Utility Move', '1 Bonus Action', 'Self', 'Physique / Agility', 'Berhasil melewati tembok, pagar, atau rintangan tinggi tanpa check, sekali per Short Rest.', 'Teknik panjat yang sudah terlatih membuat segala dinding bukan halangan.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, move_type = EXCLUDED.move_type, cost = EXCLUDED.cost, range = EXCLUDED.range, check_type = EXCLUDED.check_type, effect = EXCLUDED.effect, description = EXCLUDED.description;
INSERT INTO public.ekskul (id, name, tagline, hit_die, primary_stat, saving_throws, perk_description) VALUES ('penyiaran', 'Penyiaran (Broadcasting / Radio Sekolah)', 'Suara Emas Penguasa Speaker Sekolah & Intel Gosip', 'd6', 'Looks / Intelligent', ARRAY['intelligent', 'looks']::TEXT[], 'Hak akses ruang siaran audio sekolah, mikrofon, pemutar lagu, dan jaringan informan gosip paling mutakhir di sekolah.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, tagline = EXCLUDED.tagline, hit_die = EXCLUDED.hit_die, primary_stat = EXCLUDED.primary_stat, saving_throws = EXCLUDED.saving_throws, perk_description = EXCLUDED.perk_description;
INSERT INTO public.ekskul_subclasses (id, ekskul_id, name, description) VALUES ('radio_host', 'penyiaran', 'Penyiar Radio Sekolah', 'Suara emas sekolah. Semua Social Moves berbasis suara mendapat +1 ke DC check dan 1d4 bonus damage.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description;
INSERT INTO public.ekskul_subclasses (id, ekskul_id, name, description) VALUES ('investigator', 'penyiaran', 'Reporter Investigasi', 'Ahli menggali informasi. Advantage pada semua check Intelligent (Street) dan Mind (Interpersonal) untuk mencari gosip.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description;
INSERT INTO public.ekskul_moves (id, ekskul_id, name, move_type, cost, range, check_type, effect, description) VALUES ('penyiaran_move_1', 'penyiaran', 'Pengumuman Speaker Sekolah (Public Broadcast)', 'Utility / Social Move', '1 Aksi Khusus', 'Seluruh Sekolah', 'Looks / Influence', 'Menyampaikan pesan ke seluruh sekolah. Target gosip mengalami 1d8 Composure damage jika nama mereka disebut.', 'Menyalakan mixer audio dan menyiarkan informasi menggemparkan lewat speaker sekolah.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, move_type = EXCLUDED.move_type, cost = EXCLUDED.cost, range = EXCLUDED.range, check_type = EXCLUDED.check_type, effect = EXCLUDED.effect, description = EXCLUDED.description;
INSERT INTO public.ekskul_moves (id, ekskul_id, name, move_type, cost, range, check_type, effect, description) VALUES ('penyiaran_move_2', 'penyiaran', 'Modulasi Suara Menghanyutkan (Soothing ASMR Voice)', 'Social Move', '1 Action', '30 ft', 'Looks / Charm vs Target Mind Save', 'Target tidak bisa mengambil aksi agresif selama 1 giliran karena terpesona.', 'Berbicara dengan intonasi merdu dan menenangkan seperti penyiar podcast malam hari.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, move_type = EXCLUDED.move_type, cost = EXCLUDED.cost, range = EXCLUDED.range, check_type = EXCLUDED.check_type, effect = EXCLUDED.effect, description = EXCLUDED.description;
INSERT INTO public.ekskul_moves (id, ekskul_id, name, move_type, cost, range, check_type, effect, description) VALUES ('penyiaran_move_3', 'penyiaran', 'Bocoran Intel Eksklusif (Exclusive Scoop)', 'Utility Move', '10 Menit', 'Self', 'Intelligent / Street', 'Mendapatkan 1 informasi rahasia atau rumor akurat tentang karakter atau situasi yang diinginkan dari jaringan informan.', 'Mengontak sumber rahasia di balik layar untuk mengumpulkan intel terbaru sebelum aksi.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, move_type = EXCLUDED.move_type, cost = EXCLUDED.cost, range = EXCLUDED.range, check_type = EXCLUDED.check_type, effect = EXCLUDED.effect, description = EXCLUDED.description;
INSERT INTO public.ekskul (id, name, tagline, hit_die, primary_stat, saving_throws, perk_description) VALUES ('literatur', 'Literatur (Klub Sastra & Membaca)', 'Kekuatan Kata Romantis, Sajak & Misteri Buku Lama', 'd6', 'Intelligent / Mind', ARRAY['intelligent', 'mind']::TEXT[], 'Tempat persembunyian tenang di sudut perpustakaan, koleksi novel romansa klasik, kemampuan merangkai surat cinta mematikan.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, tagline = EXCLUDED.tagline, hit_die = EXCLUDED.hit_die, primary_stat = EXCLUDED.primary_stat, saving_throws = EXCLUDED.saving_throws, perk_description = EXCLUDED.perk_description;
INSERT INTO public.ekskul_subclasses (id, ekskul_id, name, description) VALUES ('novelist', 'literatur', 'Penulis Puisi & Novel Romansa', 'Surat cinta dan aksi romansa berbasis Talent/Creative mendapat 1d4 bonus damage Composure.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description;
INSERT INTO public.ekskul_subclasses (id, ekskul_id, name, description) VALUES ('archivist', 'literatur', 'Penjaga Arsip Sejarah Sekolah', 'Ahli sejarah dan dokumen. Advantage pada semua check Intelligent terkait sejarah, peraturan, atau informasi tertulis.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description;
INSERT INTO public.ekskul_moves (id, ekskul_id, name, move_type, cost, range, check_type, effect, description) VALUES ('literatur_move_1', 'literatur', 'Surat Cinta Puitis (Lethal Love Letter)', 'Romance Move', 'Dibuat saat istirahat', 'Loker / Meja Belajar', 'Talent / Creative vs Target Mind Save', 'Target kehilangan 2d6 Composure dan Heart Meter naik +1 ♥.', 'Menyelipkan sepucuk surat wangi berhias kata-kata puitis mendalam di loker sepatu target.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, move_type = EXCLUDED.move_type, cost = EXCLUDED.cost, range = EXCLUDED.range, check_type = EXCLUDED.check_type, effect = EXCLUDED.effect, description = EXCLUDED.description;
INSERT INTO public.ekskul_moves (id, ekskul_id, name, move_type, cost, range, check_type, effect, description) VALUES ('literatur_move_2', 'literatur', 'Membaca Pola Pikiran (Literary Empathy)', 'Utility Move', '1 Action', '15 ft', 'Mind / Interpersonal', 'Mengetahui satu keinginan terbesar atau rasa bersalah rahasia dari target yang sedang berbicara.', 'Menganalisis pilihan kata dan jeda napas seseorang layaknya membaca narasi tokoh novel.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, move_type = EXCLUDED.move_type, cost = EXCLUDED.cost, range = EXCLUDED.range, check_type = EXCLUDED.check_type, effect = EXCLUDED.effect, description = EXCLUDED.description;
INSERT INTO public.ekskul_moves (id, ekskul_id, name, move_type, cost, range, check_type, effect, description) VALUES ('literatur_move_3', 'literatur', 'Kutipan Menghancurkan (Devastating Quote)', 'Social Attack', '1 Action', '20 ft', 'Intelligent / Academic vs Target Mind Save', 'Target kehilangan 1d8 Composure karena argumennya terbantahkan sempurna oleh kata-kata tertulis.', 'Mengutip paragraf dari buku atau tulisan sendiri yang secara tepat membungkam argumen lawan.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, move_type = EXCLUDED.move_type, cost = EXCLUDED.cost, range = EXCLUDED.range, check_type = EXCLUDED.check_type, effect = EXCLUDED.effect, description = EXCLUDED.description;
INSERT INTO public.ekskul (id, name, tagline, hit_die, primary_stat, saving_throws, perk_description) VALUES ('band', 'Band Musik (Gitar / Drum / Vokal / Keyboard)', 'Dentuman Distorsi, Semangat Jiwa Muda & Fans Fanatik', 'd8', 'Looks / Talent', ARRAY['looks', 'talent']::TEXT[], 'Studio musik kedap suara, instrumen musik andalan, ampli portabel, pick gitar jimat keberuntungan, dan basis penggemar.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, tagline = EXCLUDED.tagline, hit_die = EXCLUDED.hit_die, primary_stat = EXCLUDED.primary_stat, saving_throws = EXCLUDED.saving_throws, perk_description = EXCLUDED.perk_description;
INSERT INTO public.ekskul_subclasses (id, ekskul_id, name, description) VALUES ('lead_guitar', 'band', 'Lead Guitarist / Soloist', 'Ahli solo gitar. Serangan Sonic berbasis Talent mendapat +1d6 damage dan bisa mempengaruhi area lebih luas.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description;
INSERT INTO public.ekskul_subclasses (id, ekskul_id, name, description) VALUES ('vocalist', 'band', 'Vokalis Utama Karismatik', 'Ahli memikat hati penonton. Semua Social Moves dari vokalis memberikan Disadvantage pada Mental Saves target.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description;
INSERT INTO public.ekskul_moves (id, ekskul_id, name, move_type, cost, range, check_type, effect, description) VALUES ('band_move_1', 'band', 'Petikan Melodi Penyelamat (Bardic Rock Riff)', 'Buff Move', '1 Bonus Action', '30 ft', 'Talent / Performance', 'Memberikan 1d6 Inspiration Die ke teman. Dadu ini dapat ditambahkan ke d20 roll berikutnya dalam 10 menit.', 'Memetik melodi gitar akustik atau bersenandung nada penyemangat yang membakar antusiasme teman.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, move_type = EXCLUDED.move_type, cost = EXCLUDED.cost, range = EXCLUDED.range, check_type = EXCLUDED.check_type, effect = EXCLUDED.effect, description = EXCLUDED.description;
INSERT INTO public.ekskul_moves (id, ekskul_id, name, move_type, cost, range, check_type, effect, description) VALUES ('band_move_2', 'band', 'Distorsi Pemecah Telinga (Sonic Screech)', 'Attack / Social Move', '1 Action', '15 ft Cone', 'Physique Save DC 8+Prof+Mod Talent', '1d8 Thunder/Mental Damage ke Composure & HP fisik. Target gagal: Deafened 1 turn.', 'Mendekatkan mikrofon ke speaker monitor hingga dengkingan feedback memekakkan telinga.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, move_type = EXCLUDED.move_type, cost = EXCLUDED.cost, range = EXCLUDED.range, check_type = EXCLUDED.check_type, effect = EXCLUDED.effect, description = EXCLUDED.description;
INSERT INTO public.ekskul_moves (id, ekskul_id, name, move_type, cost, range, check_type, effect, description) VALUES ('band_move_3', 'band', 'Penampilan Epik (Crowd Performance)', 'Social Move', '1 Menit', 'Area (semua yang mendengar)', 'Talent / Performance vs Target Mind Save', 'Seluruh target yang mendengar kehilangan 1d4 Composure (terpukau) atau memulihkan 1d4 Composure (terinspirasi) — DM pilih efek berdasarkan konteks.', 'Membawakan satu lagu atau penampilan musik pendek yang mempengaruhi emosi semua orang yang hadir.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, move_type = EXCLUDED.move_type, cost = EXCLUDED.cost, range = EXCLUDED.range, check_type = EXCLUDED.check_type, effect = EXCLUDED.effect, description = EXCLUDED.description;
INSERT INTO public.ekskul (id, name, tagline, hit_die, primary_stat, saving_throws, perk_description) VALUES ('painting', 'Painting (Klub Seni Rupa & Desain)', 'Goresan Kuas, Memori Visual Tajam & Estetika Warna', 'd6', 'Talent / Intelligent', ARRAY['intelligent', 'talent']::TEXT[], 'Ruang seni penuh aroma cat minyak, kuas dan kanvas, celemek berlumur cat artistik, dan mata yang peka warna emosi.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, tagline = EXCLUDED.tagline, hit_die = EXCLUDED.hit_die, primary_stat = EXCLUDED.primary_stat, saving_throws = EXCLUDED.saving_throws, perk_description = EXCLUDED.perk_description;
INSERT INTO public.ekskul_subclasses (id, ekskul_id, name, description) VALUES ('portrait', 'painting', 'Pelukis Potret Realis', 'Ahli memvisualisasikan seseorang dari ingatan. Advantage pada check yang membutuhkan deskripsi rupa atau pengenalan wajah.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description;
INSERT INTO public.ekskul_subclasses (id, ekskul_id, name, description) VALUES ('designer', 'painting', 'Ilustrator Manga & Desain', 'Ahli visual komunikasi. Bisa menciptakan publikasi, flyer, atau karikatur yang memberikan 1d6 bonus Influence di lingkungan sekolah.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description;
INSERT INTO public.ekskul_moves (id, ekskul_id, name, move_type, cost, range, check_type, effect, description) VALUES ('painting_move_1', 'painting', 'Sketsa Wajah Kilat (Photographic Sketch)', 'Utility Move', '1 Menit', 'Touch', 'Talent / Creative', 'Menghasilkan potret visual presisi dari seseorang atau barang bukti yang hanya sempat dilihat sekilas.', 'Menggoreskan pensil 2B di buku sketsa dengan kecepatan tangan mengagumkan.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, move_type = EXCLUDED.move_type, cost = EXCLUDED.cost, range = EXCLUDED.range, check_type = EXCLUDED.check_type, effect = EXCLUDED.effect, description = EXCLUDED.description;
INSERT INTO public.ekskul_moves (id, ekskul_id, name, move_type, cost, range, check_type, effect, description) VALUES ('painting_move_2', 'painting', 'Cipratan Cat Distraksi (Paint Splatter Blind)', 'Attack / Utility Move', '1 Action', '10 ft', 'Physique / Agility', 'Target Blinded selama 1 giliran hingga menyeka cat dari mata mereka.', 'Menyiramkan palet cat minyak basah tepat ke arah wajah lawan.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, move_type = EXCLUDED.move_type, cost = EXCLUDED.cost, range = EXCLUDED.range, check_type = EXCLUDED.check_type, effect = EXCLUDED.effect, description = EXCLUDED.description;
INSERT INTO public.ekskul_moves (id, ekskul_id, name, move_type, cost, range, check_type, effect, description) VALUES ('painting_move_3', 'painting', 'Karya Provokasi (Satirical Artwork)', 'Social Move', '1 Jam (luar sesi)', 'Area Sekolah', 'Talent / Creative vs Target Looks Save', 'Karya visual yang menyindir target memicu gosip. Target kehilangan 1d4 Composure setiap kali ada murid lain melihat karya tersebut selama 1 hari.', 'Membuat karikatur atau poster satire yang dipasang diam-diam di papan pengumuman sekolah.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, move_type = EXCLUDED.move_type, cost = EXCLUDED.cost, range = EXCLUDED.range, check_type = EXCLUDED.check_type, effect = EXCLUDED.effect, description = EXCLUDED.description;

-- 3. Archetypes (Species / Tropes) & Archetype Moves
INSERT INTO public.archetypes (id, name, tagline, stat_bonus, perk_description) VALUES ('delinquent', 'Delinquent (Berandalan / Yanki)', 'Seragam Dasi Longgar, Tatapan Tajam & Hati Emas Tersembunyi', '{"physique":2,"looks":1}'::jsonb, NULL) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, tagline = EXCLUDED.tagline, stat_bonus = EXCLUDED.stat_bonus, perk_description = EXCLUDED.perk_description;
INSERT INTO public.archetype_moves (id, archetype_id, name, move_type, cost, range, check_type, effect, description) VALUES ('delinquent_move_1', 'delinquent', 'Tatapan Intimidasi (Killer Glare)', 'Social Attack', '1 Action', '15 ft', 'Looks / Aura vs Target Mind Save', 'Target kehilangan 1d6 Composure dan Disadvantage pada serangan pertama mereka di ronde ini.', 'Memandang tajam dengan tatapan dingin tanpa kedip yang membuat nyali lawan ciut seketika.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, move_type = EXCLUDED.move_type, cost = EXCLUDED.cost, range = EXCLUDED.range, check_type = EXCLUDED.check_type, effect = EXCLUDED.effect, description = EXCLUDED.description;
INSERT INTO public.archetype_moves (id, archetype_id, name, move_type, cost, range, check_type, effect, description) VALUES ('delinquent_move_2', 'delinquent', 'Gertakan Berandalan (Street Threat)', 'Social Move', 'Bonus Action', '30 ft', 'Physique / Power vs Target Mind Save', 'Target harus Wisdom Save atau tidak berani mendekat dalam jarak 10 ft selama 1 giliran.', 'Mengepalkan tangan dan berdiri tegak dengan ekspresi sangar yang tak terbantahkan.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, move_type = EXCLUDED.move_type, cost = EXCLUDED.cost, range = EXCLUDED.range, check_type = EXCLUDED.check_type, effect = EXCLUDED.effect, description = EXCLUDED.description;
INSERT INTO public.archetype_moves (id, archetype_id, name, move_type, cost, range, check_type, effect, description) VALUES ('delinquent_move_3', 'delinquent', 'Backing Geng (Street Crew)', 'Utility Move', '1x per Long Rest', 'Self', 'Intelligent / Street', 'Memanggil bantuan 1–2 NPC pendukung netral untuk membantu situasi konflik atau mencari info jalanan.', 'Menghubungi kenalan geng lama via SMS untuk meminta backup atau bantuan jalanan.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, move_type = EXCLUDED.move_type, cost = EXCLUDED.cost, range = EXCLUDED.range, check_type = EXCLUDED.check_type, effect = EXCLUDED.effect, description = EXCLUDED.description;
INSERT INTO public.archetypes (id, name, tagline, stat_bonus, perk_description) VALUES ('jock', 'Jock / Sporty', 'Bugar, Berenergi Tinggi, Semangat Pantang Menyerah', '{"physique":2,"talent":1}'::jsonb, NULL) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, tagline = EXCLUDED.tagline, stat_bonus = EXCLUDED.stat_bonus, perk_description = EXCLUDED.perk_description;
INSERT INTO public.archetype_moves (id, archetype_id, name, move_type, cost, range, check_type, effect, description) VALUES ('jock_move_1', 'jock', 'Lompatan Adrenalin (Adrenaline Rush)', 'Bonus Action', 'Bonus Action (1x per Short Rest)', 'Self', 'Otomatis', 'Pulihkan 1d8 Physical HP secara instan. Berlaku saat Physical HP di bawah setengah maksimal.', 'Memompa semangat juang dari dalam dada saat melihat temannya dalam bahaya.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, move_type = EXCLUDED.move_type, cost = EXCLUDED.cost, range = EXCLUDED.range, check_type = EXCLUDED.check_type, effect = EXCLUDED.effect, description = EXCLUDED.description;
INSERT INTO public.archetype_moves (id, archetype_id, name, move_type, cost, range, check_type, effect, description) VALUES ('jock_move_2', 'jock', 'Gaya Olahraga Memikat (Sporty Charisma)', 'Social Move', 'Pasif (Setelah olahraga)', '30 ft', 'Looks / Influence', 'Setelah melakukan aksi fisik, seluruh orang yang melihat memberikan reaksi positif. Advantage pada Looks checks selama 10 menit berikutnya.', 'Keringat bercucuran, napas terengah, dan tatapan bersinar — kombinasi yang tidak ada yang bisa tahan.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, move_type = EXCLUDED.move_type, cost = EXCLUDED.cost, range = EXCLUDED.range, check_type = EXCLUDED.check_type, effect = EXCLUDED.effect, description = EXCLUDED.description;
INSERT INTO public.archetype_moves (id, archetype_id, name, move_type, cost, range, check_type, effect, description) VALUES ('jock_move_3', 'jock', 'Teriakan Bakar Semangat (Hype Shout)', 'Buff Move', '1 Action (1x per Long Rest)', '30 ft (Seluruh Tim)', 'Physique / Stamina', 'Seluruh sekutu dalam jangkauan mendapat Advantage pada Physical Saving Throw dan Attack selama 2 giliran.', 'Berteriak lantang menyemangati seluruh tim dengan teriakan penuh energi layaknya kapten olahraga.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, move_type = EXCLUDED.move_type, cost = EXCLUDED.cost, range = EXCLUDED.range, check_type = EXCLUDED.check_type, effect = EXCLUDED.effect, description = EXCLUDED.description;
INSERT INTO public.archetypes (id, name, tagline, stat_bonus, perk_description) VALUES ('nerd', 'Nerd (Murid Ambis / Kutu Buku)', 'Kacamata Frame Tebal, Catatan Lengkap & Tahu Segalanya', '{"intelligent":2,"mind":1}'::jsonb, NULL) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, tagline = EXCLUDED.tagline, stat_bonus = EXCLUDED.stat_bonus, perk_description = EXCLUDED.perk_description;
INSERT INTO public.archetype_moves (id, archetype_id, name, move_type, cost, range, check_type, effect, description) VALUES ('nerd_move_1', 'nerd', 'Analisis Cepat (Quick Analysis)', 'Bonus Action', 'Bonus Action', 'Self / 30 ft', 'Intelligent / Academic', 'Mengidentifikasi kelemahan mekanik atau pola perilaku target. Serangan berikutmu ke target mendapat Advantage.', 'Mengamati situasi dalam hitungan detik dan langsung menghitung kemungkinan terbaik untuk bertindak.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, move_type = EXCLUDED.move_type, cost = EXCLUDED.cost, range = EXCLUDED.range, check_type = EXCLUDED.check_type, effect = EXCLUDED.effect, description = EXCLUDED.description;
INSERT INTO public.archetype_moves (id, archetype_id, name, move_type, cost, range, check_type, effect, description) VALUES ('nerd_move_2', 'nerd', 'Presentasi Fakta (Fact Check)', 'Social Attack', '1 Action', '20 ft', 'Intelligent / People vs Target Intelligent Save', 'Target kehilangan 1d6 Composure karena argumennya terbantahkan dengan data dan fakta akurat.', 'Mengutarakan fakta dan data yang membantah pernyataan lawan secara sistematis dan akurat.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, move_type = EXCLUDED.move_type, cost = EXCLUDED.cost, range = EXCLUDED.range, check_type = EXCLUDED.check_type, effect = EXCLUDED.effect, description = EXCLUDED.description;
INSERT INTO public.archetype_moves (id, archetype_id, name, move_type, cost, range, check_type, effect, description) VALUES ('nerd_move_3', 'nerd', 'Memori Fotografis (Eidetic Memory)', 'Utility Move', 'Pasif', 'Self', 'Otomatis', 'Bisa mengingat dan mereproduksi secara akurat apapun yang pernah dibaca atau dilihat dalam 24 jam terakhir tanpa roll check.', 'Memori luar biasa yang memungkinkan memanggil kembali informasi apapun kapan saja dibutuhkan.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, move_type = EXCLUDED.move_type, cost = EXCLUDED.cost, range = EXCLUDED.range, check_type = EXCLUDED.check_type, effect = EXCLUDED.effect, description = EXCLUDED.description;
INSERT INTO public.archetypes (id, name, tagline, stat_bonus, perk_description) VALUES ('class_clown', 'Class Clown (Pelawak Kelas)', 'Tukang Rusuh Positif, Pemecah Kecanggungan & Bikin Ngakak', '{"talent":2,"looks":1}'::jsonb, NULL) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, tagline = EXCLUDED.tagline, stat_bonus = EXCLUDED.stat_bonus, perk_description = EXCLUDED.perk_description;
INSERT INTO public.archetype_moves (id, archetype_id, name, move_type, cost, range, check_type, effect, description) VALUES ('class_clown_move_1', 'class_clown', 'Lelucon Pengalih Perhatian (Distraction Prank)', 'Utility Move', 'Bonus Action', '30 ft', 'Talent / Performance vs Target Mind Save', '1 target Distracted (Disadvantage pada check Perception) selama 1 giliran. Sekutu mendapat Advantage untuk beraksi di dekat target.', 'Melempar lelucon atau melakukan aksi konyol yang memaksa semua perhatian tertuju ke sana.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, move_type = EXCLUDED.move_type, cost = EXCLUDED.cost, range = EXCLUDED.range, check_type = EXCLUDED.check_type, effect = EXCLUDED.effect, description = EXCLUDED.description;
INSERT INTO public.archetype_moves (id, archetype_id, name, move_type, cost, range, check_type, effect, description) VALUES ('class_clown_move_2', 'class_clown', 'Humor Penstabil (Tension Breaker)', 'Heal Move', '1 Action (1x per Short Rest)', '30 ft', 'Talent / Adaptability', 'Memulihkan 1d6 Composure ke seluruh sekutu dalam jangkauan yang sedang stress.', 'Melempar candaan tepat waktu saat suasana paling tegang untuk memecah atmosfer yang membeku.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, move_type = EXCLUDED.move_type, cost = EXCLUDED.cost, range = EXCLUDED.range, check_type = EXCLUDED.check_type, effect = EXCLUDED.effect, description = EXCLUDED.description;
INSERT INTO public.archetype_moves (id, archetype_id, name, move_type, cost, range, check_type, effect, description) VALUES ('class_clown_move_3', 'class_clown', 'Peniruan Sempurna (Perfect Impression)', 'Social Move', '1 Action', '15 ft', 'Talent / Performance vs Target Mind Save', 'Menirukan gaya bicara atau behavior orang tertentu dengan sempurna. Target kehilangan 1d4 Composure karena malu atau marah.', 'Menirukan cara berbicara dan bergerak seseorang dengan presisi komedi yang menyentil ego target.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, move_type = EXCLUDED.move_type, cost = EXCLUDED.cost, range = EXCLUDED.range, check_type = EXCLUDED.check_type, effect = EXCLUDED.effect, description = EXCLUDED.description;
INSERT INTO public.archetypes (id, name, tagline, stat_bonus, perk_description) VALUES ('emo', 'Emo / Serius', 'Duduk di Sudut Jendela, Headphone Terpasang & Tatapan Dingin', '{"mind":2,"intelligent":1}'::jsonb, NULL) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, tagline = EXCLUDED.tagline, stat_bonus = EXCLUDED.stat_bonus, perk_description = EXCLUDED.perk_description;
INSERT INTO public.archetype_moves (id, archetype_id, name, move_type, cost, range, check_type, effect, description) VALUES ('emo_move_1', 'emo', 'Keheningan Menghantui (Eerie Silence)', 'Social Attack', '1 Action', '15 ft', 'Mind / Emotional vs Target Mind Save', 'Target kehilangan 1d6 Composure karena tidak nyaman dengan sikap acuhmu yang dingin dan tidak terduga.', 'Diam total. Tidak berkata apapun. Tidak bereaksi apapun. Dan itu justru jauh lebih mengancam dari kata-kata manapun.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, move_type = EXCLUDED.move_type, cost = EXCLUDED.cost, range = EXCLUDED.range, check_type = EXCLUDED.check_type, effect = EXCLUDED.effect, description = EXCLUDED.description;
INSERT INTO public.archetype_moves (id, archetype_id, name, move_type, cost, range, check_type, effect, description) VALUES ('emo_move_2', 'emo', 'Introspeksi Diam (Silent Contemplation)', 'Utility Move', '10 Menit istirahat', 'Self', 'Mind / Emotional', 'Memulihkan 1d8 Composure dan mendapat Advantage pada Mind Saving Throws selama 1 jam berikutnya.', 'Duduk di sudut jendela dengan headphone, menutup diri sejenak dari dunia untuk meregenerasi ketenangan batin.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, move_type = EXCLUDED.move_type, cost = EXCLUDED.cost, range = EXCLUDED.range, check_type = EXCLUDED.check_type, effect = EXCLUDED.effect, description = EXCLUDED.description;
INSERT INTO public.archetype_moves (id, archetype_id, name, move_type, cost, range, check_type, effect, description) VALUES ('emo_move_3', 'emo', 'Kata Tajam Terakhir (Cutting Remark)', 'Social Attack', 'Reaction', '15 ft', 'Intelligent / People vs Target Mind Save', 'Sebagai reaksi terhadap serangan sosial yang diterima: balikkan 1d4 Composure damage ke penyerang.', 'Satu kalimat singkat, dingin, dan tepat sasaran yang merongrong kepercayaan diri lawan lebih efektif dari pidato panjang.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, move_type = EXCLUDED.move_type, cost = EXCLUDED.cost, range = EXCLUDED.range, check_type = EXCLUDED.check_type, effect = EXCLUDED.effect, description = EXCLUDED.description;
INSERT INTO public.archetypes (id, name, tagline, stat_bonus, perk_description) VALUES ('weeb', 'Weeb (Pecinta Anime / Manga / Pop Culture)', 'Chuunibyou Nyata, Gantungan Tas Penuh Pin & Imajiner Liar', '{"talent":1,"luck":2}'::jsonb, NULL) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, tagline = EXCLUDED.tagline, stat_bonus = EXCLUDED.stat_bonus, perk_description = EXCLUDED.perk_description;
INSERT INTO public.archetype_moves (id, archetype_id, name, move_type, cost, range, check_type, effect, description) VALUES ('weeb_move_1', 'weeb', 'Teknik Rahasia Chuunibyou (Secret Technique)', 'Attack Move', '1 Action', '15 ft', 'Talent / Performance vs Target Mind Save', '1d8 Composure damage. Jika kamu berpose dramatis sambil menyebutkan nama teknik, damage meningkat jadi 1d10.', 'Memostur dramatis dan berteriak nama teknik rahasia imajinatif yang anehnya bekerja karena keyakinan kuat.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, move_type = EXCLUDED.move_type, cost = EXCLUDED.cost, range = EXCLUDED.range, check_type = EXCLUDED.check_type, effect = EXCLUDED.effect, description = EXCLUDED.description;
INSERT INTO public.archetype_moves (id, archetype_id, name, move_type, cost, range, check_type, effect, description) VALUES ('weeb_move_2', 'weeb', 'Referensi Tersembunyi (Hidden Reference)', 'Utility Move', 'Bonus Action', 'Self', 'Talent / Creative', 'Mendapat Advantage pada 1 check sosial atau kreatif berikutnya dengan mengaitkannya ke referensi anime/manga yang relevan.', 'Mengutip dialog atau strategi dari anime favorit yang ternyata benar-benar berlaku di situasi nyata ini.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, move_type = EXCLUDED.move_type, cost = EXCLUDED.cost, range = EXCLUDED.range, check_type = EXCLUDED.check_type, effect = EXCLUDED.effect, description = EXCLUDED.description;
INSERT INTO public.archetype_moves (id, archetype_id, name, move_type, cost, range, check_type, effect, description) VALUES ('weeb_move_3', 'weeb', 'Keberuntungan Flag Asmara (Lucky Romance Flag)', 'Utility Move', '1x per Long Rest', 'Self', 'Luck / Relationship Luck', 'Reroll satu d20 roll apapun dengan mengambil hasil yang lebih tinggi. Berlaku untuk check asmara atau sosial.', 'Saat yakin bahwa ''ini pasti flag romance!'', keberuntungan anime benar-benar berpihak padamu.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, move_type = EXCLUDED.move_type, cost = EXCLUDED.cost, range = EXCLUDED.range, check_type = EXCLUDED.check_type, effect = EXCLUDED.effect, description = EXCLUDED.description;
INSERT INTO public.archetypes (id, name, tagline, stat_bonus, perk_description) VALUES ('popular_kids', 'Popular Kids (Idola Sekolah / Trendsetter)', 'Senyum Menawan, Pakaian Modis & Selalu Jadi Pusat Perhatian', '{"looks":2,"mind":1}'::jsonb, NULL) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, tagline = EXCLUDED.tagline, stat_bonus = EXCLUDED.stat_bonus, perk_description = EXCLUDED.perk_description;
INSERT INTO public.archetype_moves (id, archetype_id, name, move_type, cost, range, check_type, effect, description) VALUES ('popular_kids_move_1', 'popular_kids', 'Senyum Menawan (Charming Smile)', 'Social Attack', '1 Action', '10 ft', 'Looks / Charm vs Target Mind Save', '1d6 Composure damage. Target Distracted (Disadvantage pada aksi berikutnya) karena tidak bisa fokus saat melihatmu.', 'Senyum manis yang memancarkan pesona alami, cukup untuk melumpuhkan konsentrasi siapa saja.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, move_type = EXCLUDED.move_type, cost = EXCLUDED.cost, range = EXCLUDED.range, check_type = EXCLUDED.check_type, effect = EXCLUDED.effect, description = EXCLUDED.description;
INSERT INTO public.archetype_moves (id, archetype_id, name, move_type, cost, range, check_type, effect, description) VALUES ('popular_kids_move_2', 'popular_kids', 'Pengaruh Sosial Media (Trendsetter Post)', 'Utility Move', '1x per Long Rest', 'Area Sekolah', 'Looks / Influence', 'Mempengaruhi opini umum sekolah soal satu topik/target. Target dipandang positif atau negatif oleh mayoritas murid selama 1 hari.', 'Memposting konten strategis di media sosial sekolah yang langsung mempengaruhi pandangan publik.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, move_type = EXCLUDED.move_type, cost = EXCLUDED.cost, range = EXCLUDED.range, check_type = EXCLUDED.check_type, effect = EXCLUDED.effect, description = EXCLUDED.description;
INSERT INTO public.archetype_moves (id, archetype_id, name, move_type, cost, range, check_type, effect, description) VALUES ('popular_kids_move_3', 'popular_kids', 'Koneksi VIP (Name-Drop)', 'Social Utility', 'Reaction', '30 ft', 'Looks / Influence', 'Batalkan satu tindakan negatif yang diarahkan kepadamu atau temanmu dengan menyebut nama orang berpengaruh di sekolah.', 'Menyebut nama guru favorit, ketua OSIS, atau orang tua berpengaruh yang langsung membuat situasi berbalik.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, move_type = EXCLUDED.move_type, cost = EXCLUDED.cost, range = EXCLUDED.range, check_type = EXCLUDED.check_type, effect = EXCLUDED.effect, description = EXCLUDED.description;
INSERT INTO public.archetypes (id, name, tagline, stat_bonus, perk_description) VALUES ('normies', 'Normies (Murid Biasa / Kalem)', 'Tidak Banyak Tingkah, Pengamat Damai & Menghargai Hal Simpel', '{"physique":1,"intelligent":1,"looks":1,"mind":1,"talent":1,"luck":1}'::jsonb, NULL) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, tagline = EXCLUDED.tagline, stat_bonus = EXCLUDED.stat_bonus, perk_description = EXCLUDED.perk_description;
INSERT INTO public.archetype_moves (id, archetype_id, name, move_type, cost, range, check_type, effect, description) VALUES ('normies_move_1', 'normies', 'Membaur Sempurna (Blend In)', 'Utility Move', 'Bonus Action', 'Self', 'Mind / Awareness', 'Menjadi tidak menonjol di kerumunan. Musuh yang mencari kamu harus Passive Perception DC 15 untuk menemukanmu.', 'Menyesuaikan gaya berjalan, ekspresi, dan pakaian agar tampak seperti murid biasa yang tak menarik perhatian.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, move_type = EXCLUDED.move_type, cost = EXCLUDED.cost, range = EXCLUDED.range, check_type = EXCLUDED.check_type, effect = EXCLUDED.effect, description = EXCLUDED.description;
INSERT INTO public.archetype_moves (id, archetype_id, name, move_type, cost, range, check_type, effect, description) VALUES ('normies_move_2', 'normies', 'Simpati Universal (Everybody''s Friend)', 'Social Utility', '1 Action', '15 ft', 'Mind / Interpersonal', 'Meredakan konflik antara 2 pihak yang berselisih. Kedua pihak harus berunding damai selama minimal 1 giliran.', 'Dengan ketulusan dan pendekatan kalem, menjadi jembatan damai yang diterima oleh semua kalangan.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, move_type = EXCLUDED.move_type, cost = EXCLUDED.cost, range = EXCLUDED.range, check_type = EXCLUDED.check_type, effect = EXCLUDED.effect, description = EXCLUDED.description;
INSERT INTO public.archetype_moves (id, archetype_id, name, move_type, cost, range, check_type, effect, description) VALUES ('normies_move_3', 'normies', 'Hoki Murni (Pure Luck)', 'Utility Move', '1x per Long Rest', 'Self', 'Luck / Situation Luck', 'Pilih 1 kejadian buruk yang baru saja terjadi dan batalkan (revert) hasilnya — ''kebetulan'' semua berjalan baik.', 'Kadang keberuntungan bukan soal skill atau rencana — hanya soal timing dan kebetulan yang menyelamatkan segalanya.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, move_type = EXCLUDED.move_type, cost = EXCLUDED.cost, range = EXCLUDED.range, check_type = EXCLUDED.check_type, effect = EXCLUDED.effect, description = EXCLUDED.description;

-- 4. Social Classes
INSERT INTO public.social_classes (id, name, tier, daily_allowance, initial_savings, daily_amount, savings_amount, description, starter_items) VALUES ('rich', 'Rich (Keluarga Konglomerat / Ningrat)', NULL, NULL, '¥200,000 / Rp 20,000,000', undefined, 200000, NULL, ARRAY[]::TEXT[]) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, tier = EXCLUDED.tier, daily_allowance = EXCLUDED.daily_allowance, initial_savings = EXCLUDED.initial_savings, daily_amount = EXCLUDED.daily_amount, savings_amount = EXCLUDED.savings_amount, description = EXCLUDED.description, starter_items = EXCLUDED.starter_items;
INSERT INTO public.social_classes (id, name, tier, daily_allowance, initial_savings, daily_amount, savings_amount, description, starter_items) VALUES ('medium_rich', 'Medium Rich (Keluarga Menengah Atas / Dokter / Eksekutif)', NULL, NULL, '¥50,000 / Rp 5,000,000', undefined, 50000, NULL, ARRAY[]::TEXT[]) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, tier = EXCLUDED.tier, daily_allowance = EXCLUDED.daily_allowance, initial_savings = EXCLUDED.initial_savings, daily_amount = EXCLUDED.daily_amount, savings_amount = EXCLUDED.savings_amount, description = EXCLUDED.description, starter_items = EXCLUDED.starter_items;
INSERT INTO public.social_classes (id, name, tier, daily_allowance, initial_savings, daily_amount, savings_amount, description, starter_items) VALUES ('medium', 'Medium (Keluarga Pegawai Biasa / Rata-rata)', NULL, NULL, '¥15,000 / Rp 1,500,000', undefined, 15000, NULL, ARRAY[]::TEXT[]) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, tier = EXCLUDED.tier, daily_allowance = EXCLUDED.daily_allowance, initial_savings = EXCLUDED.initial_savings, daily_amount = EXCLUDED.daily_amount, savings_amount = EXCLUDED.savings_amount, description = EXCLUDED.description, starter_items = EXCLUDED.starter_items;
INSERT INTO public.social_classes (id, name, tier, daily_allowance, initial_savings, daily_amount, savings_amount, description, starter_items) VALUES ('medium_poor', 'Medium Poor (Keluarga Pas-pasan / Berhemat)', NULL, NULL, '¥5,000 / Rp 500,000', undefined, 5000, NULL, ARRAY[]::TEXT[]) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, tier = EXCLUDED.tier, daily_allowance = EXCLUDED.daily_allowance, initial_savings = EXCLUDED.initial_savings, daily_amount = EXCLUDED.daily_amount, savings_amount = EXCLUDED.savings_amount, description = EXCLUDED.description, starter_items = EXCLUDED.starter_items;
INSERT INTO public.social_classes (id, name, tier, daily_allowance, initial_savings, daily_amount, savings_amount, description, starter_items) VALUES ('poor', 'Poor (Keluarga Kurang Mampu / Pejuang Hidup)', NULL, NULL, '¥1,000 / Rp 100,000 (Di celengan)', undefined, 1000, NULL, ARRAY[]::TEXT[]) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, tier = EXCLUDED.tier, daily_allowance = EXCLUDED.daily_allowance, initial_savings = EXCLUDED.initial_savings, daily_amount = EXCLUDED.daily_amount, savings_amount = EXCLUDED.savings_amount, description = EXCLUDED.description, starter_items = EXCLUDED.starter_items;
INSERT INTO public.social_classes (id, name, tier, daily_allowance, initial_savings, daily_amount, savings_amount, description, starter_items) VALUES ('orphanage', 'Orphanage (Anak Asuh Panti / Hidup Mandiri)', NULL, NULL, '¥3,000 / Rp 300,000', undefined, 3000, NULL, ARRAY[]::TEXT[]) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, tier = EXCLUDED.tier, daily_allowance = EXCLUDED.daily_allowance, initial_savings = EXCLUDED.initial_savings, daily_amount = EXCLUDED.daily_amount, savings_amount = EXCLUDED.savings_amount, description = EXCLUDED.description, starter_items = EXCLUDED.starter_items;

-- 5. Equipment Packs

-- 6. Basic Actions
INSERT INTO public.basic_actions (id, name, category, cost, check_type, effect, description) VALUES ('action_1', 'Pukulan Fisik (Unarmed Strike)', 'basic_combat', NULL, 'Physique / Power', NULL, 'Tinju mentah atau tamparan spontan saat adu fisik jarak dekat.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, cost = EXCLUDED.cost, check_type = EXCLUDED.check_type, effect = EXCLUDED.effect, description = EXCLUDED.description;
INSERT INTO public.basic_actions (id, name, category, cost, check_type, effect, description) VALUES ('action_2', 'Tendangan Cepat (Snap Kick)', 'basic_combat', NULL, 'Physique / Agility', NULL, 'Tendangan mendadak mengarah ke betis atau paha lawan.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, cost = EXCLUDED.cost, check_type = EXCLUDED.check_type, effect = EXCLUDED.effect, description = EXCLUDED.description;
INSERT INTO public.basic_actions (id, name, category, cost, check_type, effect, description) VALUES ('action_3', 'Dorongan Kuat (Shove)', 'basic_combat', NULL, 'Physique / Power vs Target Physique Save', NULL, 'Mendorong lawan dengan kedua tangan penuh tenaga agar kehilangan keseimbangan.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, cost = EXCLUDED.cost, check_type = EXCLUDED.check_type, effect = EXCLUDED.effect, description = EXCLUDED.description;
INSERT INTO public.basic_actions (id, name, category, cost, check_type, effect, description) VALUES ('action_4', 'Tangkis & Bertahan (Dodge & Guard)', 'basic_combat', NULL, 'Otomatis', NULL, 'Memasang kuda-kuda rapat dan fokus memperhatikan gerak-gerik lawan.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, cost = EXCLUDED.cost, check_type = EXCLUDED.check_type, effect = EXCLUDED.effect, description = EXCLUDED.description;
INSERT INTO public.basic_actions (id, name, category, cost, check_type, effect, description) VALUES ('action_5', 'Kabur & Menghindar (Disengage)', 'basic_combat', NULL, 'Physique / Agility', NULL, 'Mundur dengan langkah cerdas memanfaatkan celah gerak lawan.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, cost = EXCLUDED.cost, check_type = EXCLUDED.check_type, effect = EXCLUDED.effect, description = EXCLUDED.description;
INSERT INTO public.basic_actions (id, name, category, cost, check_type, effect, description) VALUES ('action_6', 'Tatapan Intimidasi (Intimidating Stare)', 'basic_social', NULL, 'Looks / Aura vs Target Mind Save', 'Target ragu bertindak (Disadvantage aksi berikutnya).', 'Menatap dengan ekspresi dingin dan intensitas yang membuat target tidak nyaman.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, cost = EXCLUDED.cost, check_type = EXCLUDED.check_type, effect = EXCLUDED.effect, description = EXCLUDED.description;
INSERT INTO public.basic_actions (id, name, category, cost, check_type, effect, description) VALUES ('action_7', 'Senyuman Persuasi (Charming Smile)', 'basic_social', NULL, 'Looks / Charm vs Target Mind Save', 'Target tertegun sejenak; Disadvantage pada save berikutnya.', 'Memberikan senyuman tulus yang membuat degup jantung target berdebar kencang.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, cost = EXCLUDED.cost, check_type = EXCLUDED.check_type, effect = EXCLUDED.effect, description = EXCLUDED.description;
INSERT INTO public.basic_actions (id, name, category, cost, check_type, effect, description) VALUES ('action_8', 'Sindiran / Provokasi (Taunt)', 'basic_social', NULL, 'Intelligent / People vs Target Mind Save', 'Target terprovokasi: wajib fokus menyerangmu pada gilirannya.', 'Melontarkan kata-kata tajam yang tepat sasaran untuk memancing reaksi emosional target.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, cost = EXCLUDED.cost, check_type = EXCLUDED.check_type, effect = EXCLUDED.effect, description = EXCLUDED.description;
INSERT INTO public.basic_actions (id, name, category, cost, check_type, effect, description) VALUES ('action_9', 'Rayuan Halus (Subtle Flirt)', 'basic_social', NULL, 'Looks / Charm vs Target Mind Save', 'Jika berhasil, target memberikan Advantage pada percakapan sosial berikutnya denganmu.', 'Mengirimkan sinyal halus lewat tatapan atau gestur kecil yang membuka pintu percakapan.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, cost = EXCLUDED.cost, check_type = EXCLUDED.check_type, effect = EXCLUDED.effect, description = EXCLUDED.description;
INSERT INTO public.basic_actions (id, name, category, cost, check_type, effect, description) VALUES ('action_10', 'Bantuan & Dukungan (Help / Support)', 'basic_social', NULL, 'Mind / Interpersonal', 'Memberikan Advantage kepada 1 sekutu pada roll check atau serangan berikutnya.', 'Membantu, mendukung, atau memberikan ide kepada teman yang sedang berusaha melakukan sesuatu.') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, cost = EXCLUDED.cost, check_type = EXCLUDED.check_type, effect = EXCLUDED.effect, description = EXCLUDED.description;

-- 7. Calendar Events
INSERT INTO public.calendar_events (id, term, name, event_type, description) VALUES ('cal_01', 'Semester 1 (Musim Semi)', 'Upacara Masuk & Pembagian Kelas Baru', NULL, 'Momen berkenalan dengan teman sebangku dan melihat siapa yang satu kelas denganmu.') ON CONFLICT (id) DO UPDATE SET term = EXCLUDED.term, name = EXCLUDED.name, event_type = EXCLUDED.event_type, description = EXCLUDED.description;
INSERT INTO public.calendar_events (id, term, name, event_type, description) VALUES ('cal_02', 'Semester 1', 'Ujian Tengah Semester (UTS / Midterms)', NULL, 'Pertaruhan nilai akademis, begadang kelompok belajar di perpustakaan.') ON CONFLICT (id) DO UPDATE SET term = EXCLUDED.term, name = EXCLUDED.name, event_type = EXCLUDED.event_type, description = EXCLUDED.description;
INSERT INTO public.calendar_events (id, term, name, event_type, description) VALUES ('cal_03', 'Semester 1', 'Festival Olahraga (Undoukai)', NULL, 'Lari estafet, tarik tambang, dan kesempatan menyemangati gebetan dari pinggir lapangan.') ON CONFLICT (id) DO UPDATE SET term = EXCLUDED.term, name = EXCLUDED.name, event_type = EXCLUDED.event_type, description = EXCLUDED.description;
INSERT INTO public.calendar_events (id, term, name, event_type, description) VALUES ('cal_04', 'Liburan Semester 1', 'Liburan Musim Panas & Festival Kembang Api', NULL, 'Mengenakan pakaian Yukata, janjian nonton kembang api kuil di malam hari.') ON CONFLICT (id) DO UPDATE SET term = EXCLUDED.term, name = EXCLUDED.name, event_type = EXCLUDED.event_type, description = EXCLUDED.description;
INSERT INTO public.calendar_events (id, term, name, event_type, description) VALUES ('cal_05', 'Semester 2 (Musim Gugur)', 'Festival Budaya Sekolah (Bunkasai)', NULL, 'Acara puncak tahunan! Rumah hantu, maid cafe kelas, dan konser band panggung sekolah.') ON CONFLICT (id) DO UPDATE SET term = EXCLUDED.term, name = EXCLUDED.name, event_type = EXCLUDED.event_type, description = EXCLUDED.description;
INSERT INTO public.calendar_events (id, term, name, event_type, description) VALUES ('cal_06', 'Semester 2', 'Study Tour Sekolah (Shuugakuryokou)', NULL, 'Perjalanan bus menginap ke Kyoto/daerah wisata; curhat rahasia malam hari di kamar hotel.') ON CONFLICT (id) DO UPDATE SET term = EXCLUDED.term, name = EXCLUDED.name, event_type = EXCLUDED.event_type, description = EXCLUDED.description;
INSERT INTO public.calendar_events (id, term, name, event_type, description) VALUES ('cal_07', 'Semester 2 (Musim Dingin)', 'Hari Valentine & White Day', NULL, 'Menaruh cokelat honmei (cinta tulus) atau giri (pertemanan) di dalam loker sepatu.') ON CONFLICT (id) DO UPDATE SET term = EXCLUDED.term, name = EXCLUDED.name, event_type = EXCLUDED.event_type, description = EXCLUDED.description;
INSERT INTO public.calendar_events (id, term, name, event_type, description) VALUES ('cal_08', 'Akhir Tahun Ajaran', 'Ujian Kenaikan Kelas & Upacara Kelulusan', NULL, 'Pengumuman kelulusan dan momen perpisahan yang penuh air mata kenangan.') ON CONFLICT (id) DO UPDATE SET term = EXCLUDED.term, name = EXCLUDED.name, event_type = EXCLUDED.event_type, description = EXCLUDED.description;
